---
title: "Bind survey data"
---

*R/bindings.R*

## bind_survey_data

## Description
 Bind survey data 


## Usage
```r
 
bind_survey_data( 
  ., 
  questions_data = NULL, 
  questions_categorical = NULL, 
  questions_continuous = NULL, 
  questions_places = NULL, 
  questions_labels = NULL, 
  questions_filter = NULL, 
  questions_animaton_id = NULL, 
  questions_add_to_popup_panel = NULL, 
  group_order_data = NULL, 
  group_order_categories = NULL, 
  label_overrides_data = NULL, 
  label_overrides_original_label = NULL, 
  label_overrides_new_label = NULL, 
  color_overrides_data = NULL, 
  color_overrides_original_question = NULL, 
  color_overrides_original_answer = NULL, 
  color_overrides_new_color = NULL, 
  places_data = NULL, 
  places_latitude = NULL, 
  places_longitude = NULL, 
  places_name = NULL, 
  grouped_questions_data = NULL, 
  grouped_questions_group = NULL, 
  grouped_questions_question = NULL, 
  grouped_questions_new_question = NULL, 
  grouped_questions_affirmative_answers = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| questions_data | A data frame for survey questions |
| questions_categorical | Each of these columns appears in the “Group by”, “Shade by” and “Compare” dropdowns. |
| questions_continuous | Must contain numbers. Each of these columns appears in the “Size by” dropdown. |
| questions_places | Must contain place names matching those specified in the “Places” sheet. Keep NULL to disable the map mode. |
| questions_labels | A column containing text (e.g. names or emoji) to write on the dots. Not recommended for datasets with more than a few hundred dots. |
| questions_filter | Add a time slider or menu to filter the data based on the contents of a single column. |
| questions_animaton_id | Specify to allow animations between multiple occurrences of the same person or thing – e.g. when using a time slider. |
| questions_add_to_popup_panel | Information to make available in the popups |
| group_order_data | Group order data frame |
| group_order_categories | Use one column for each question or metric. Put the column header from the main data sheet at the top (e.g. "Do you agree?"), followed by the answers in the order you want (e.g. "disagree", "neutral", "agree") |
| label_overrides_data | Label overrides data frame |
| label_overrides_original_label | A column of labels containing phrases from the main data sheet |
| label_overrides_new_label | New label to replace original label |
| color_overrides_data | Color overrides data frame |
| color_overrides_original_question | A column containing questions from the main data sheet |
| color_overrides_original_answer | A column containing answers from the main data sheet |
| color_overrides_new_color | New color to override Q&A. |
| places_data | Places data frame |
| places_latitude | Places latitude |
| places_longitude | Places longitude |
| places_name | Places name. Must match `questions_places`. |
| grouped_questions_data | Grouped questions data frame |
| grouped_questions_group | This column will contain the name of the grouped question. |
| grouped_questions_question | This column will contain the original question. |
| grouped_questions_new_question | This column will contain the new question. |
| grouped_questions_affirmative_answers | The respondent is included in the group if their answer to the question is one of the answers listed in these columns |






## See Also
 Other Flourish quizzes, surveys, and tables:  `bind_quiz_data()`, `bind_table_data()`, `set_quiz_details()`, `set_survey_details()`, `set_table_details()` 

