---
title: "Bind animated map data over time"
---

*R/bindings.R*

## bind_time_map_data

## Description
 Bind animated map data over time 


## Usage
```r
 
bind_time_map_data( 
  ., 
  regions_data = NULL, 
  regions_geometry = NULL, 
  regions_name = NULL, 
  regions_value = NULL, 
  regions_height = NULL, 
  regions_category = NULL, 
  regions_add_to_popup_panel = NULL, 
  inset_regions_data = NULL, 
  inset_regions_geometry = NULL, 
  events_data = NULL, 
  events_latitude = NULL, 
  events_longitude = NULL, 
  events_size = NULL, 
  events_color = NULL, 
  events_group = NULL, 
  events_start_timestamp = NULL, 
  events_end_timestamp = NULL, 
  events_animation_group = NULL, 
  events_animation_category = NULL, 
  events_animation_count = NULL, 
  events_add_to_popup_panel = NULL, 
  events_label = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| regions_data | Data (an `sf` dataframe) |
| regions_geometry | Geometry column |
| regions_name | Name of each region |
| regions_value | Value |
| regions_height | Height of Z-axis |
| regions_category | Category by which to group regions |
| regions_add_to_popup_panel | A vector of interest for tooltips. |
| inset_regions_data | Data (an `sf` data frame) |
| inset_regions_geometry | Geometry column |
| events_data | Data (data frame) |
| events_latitude | Latitude (Y axis) |
| events_longitude | Longitude (X axis) |
| events_size | Determines the size of the circles. |
| events_color | Determines the color of the circles. |
| events_group | Group points |
| events_start_timestamp | Determines when the circles appear. If left blank all the points will appear at once. If selected, creates a timeline and shows points over time. The date format must be specified in the settings panel. |
| events_end_timestamp | Determines when the circles disappear. If not specified the circle remains for the default duration specified in the settings panel. |
| events_animation_group | Use this to animate points between different values at different times in the timeline. Rows with the same content will animate from one set of values to another based on their start time. |
| events_animation_category | Used to categorise points, and to determine their color when using a categorical color palette. |
| events_animation_count | Determines how much each row is counted for by the counter. If not bound to a column, each row's count is treated as one. |
| events_add_to_popup_panel | One or more columns to show in the popups |
| events_label | label |


## Section

## Regions

 NA 

## Minimap

 NA 

## Events/points

 NA 




## See Also
 Other Flourish map:  `bind_arc_map_data()`, `bind_choropleth_map_data()`, `bind_connections_globe_data()`, `bind_region_marker_map_data()`, `set_arc_map_details()`, `set_choropleth_map_details()`, `set_connections_globe_details()`, `set_marker_map_details()`, `set_region_map_details()`, `set_time_map_details()` 

