---
title: "Bind radar chart data"
---

*R/bindings.R*

## bind_radar_data

## Description
 Bind radar chart data 


## Usage
```r
 
bind_radar_data( 
  ., 
  data = NULL, 
  name = NULL, 
  value = NULL, 
  filter = NULL, 
  color_category = NULL, 
  grid = NULL, 
  add_to_panel_popup = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| data | A radar data set. |
| name | A text column containing a name for each radar |
| value | Select three or more numerical columns |
| filter | If set, creates a filter menu or time slider |
| color_category | Add a category to color by. If empty, the "name" column will be used for colors. |
| grid | Create one column for each grouping you want to allow |
| add_to_panel_popup | Add any columns here containing extra content to show in the popups |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

