---
title: "Bind chord data"
---

*R/bindings.R*

## bind_chord_diagram_data

## Description
 Bind chord data 


## Usage
```r
 
bind_chord_diagram_data( 
  ., 
  data = NULL, 
  source_name = NULL, 
  target_name = NULL, 
  value = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| data | A data frame |
| source_name | source |
| target_name | target |
| value | A numerical value used to set the thickness of the links. |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

