---
title: "Bind card data"
---

*R/bindings.R*

## bind_card_data

## Description
 Bind card data 


## Usage
```r
 
bind_card_data( 
  ., 
  data = NULL, 
  title = NULL, 
  image_url = NULL, 
  category = NULL, 
  subtitle = NULL, 
  text = NULL, 
  audio = NULL, 
  filter = NULL, 
  add_to_popup_panel = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| data | Data frame |
| title | title |
| image_url | image URL |
| category | Optional category column to colour the cards |
| subtitle | subtitle |
| text | text |
| audio | Add an audio file to the card, which will play when the card is clicked. This will disable popup behavior. |
| filter | filter |
| add_to_popup_panel | Add any columns here containing extra content to show in the popups |






## See Also
 Other Other Flourish graphs:  `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

