---
title: "Set up Flourish panels"
---

*R/chart.R*

## chart_panels

## Description
 Set up Flourish panels 


## Usage
```r
 
chart_panels( 
  ., 
  panel_position = NULL, 
  panel_open_duration = NULL, 
  panel_side_fixed = NULL, 
  panel_side_default_content = NULL, 
  panel_custom_header = NULL, 
  panel_custom_main_text = NULL, 
  panel_width_percent = NULL, 
  panel_height_percent = NULL, 
  panel_max_width_pixels = NULL, 
  panel_max_height_pixels = NULL, 
  panel_vertical_position = NULL, 
  panel_text_color = NULL, 
  panel_font_size = NULL, 
  panel_align = NULL, 
  panel_background_color = NULL, 
  panel_background_opacity = NULL, 
  panel_padding = NULL, 
  panel_radius = NULL, 
  panel_list_type = NULL, 
  panel_list_label_weight = NULL, 
  panel_list_separator = NULL, 
  panel_shadow = NULL, 
  map_point_panel_position = NULL, 
  map_point_panel_open_duration = NULL, 
  map_point_panel_side_fixed = NULL, 
  map_point_panel_side_default_content = NULL, 
  map_point_panel_custom_header = NULL, 
  map_point_panel_custom_main_text = NULL, 
  map_point_panel_width_percent = NULL, 
  map_point_panel_height_percent = NULL, 
  map_point_panel_max_width_pixels = NULL, 
  map_point_panel_max_height_pixels = NULL, 
  map_point_panel_vertical_position = NULL, 
  map_point_panel_text_color = NULL, 
  map_point_panel_font_size = NULL, 
  map_point_panel_align = NULL, 
  map_point_panel_background_color = NULL, 
  map_point_panel_background_opacity = NULL, 
  map_point_panel_padding = NULL, 
  map_point_panel_radius = NULL, 
  map_point_panel_list_type = NULL, 
  map_point_panel_list_label_weight = NULL, 
  map_point_panel_list_separator = NULL, 
  map_point_panel_shadow = NULL, 
  map_region_panel_position = NULL, 
  map_region_panel_open_duration = NULL, 
  map_region_panel_side_fixed = NULL, 
  map_region_panel_side_default_content = NULL, 
  map_region_panel_custom_header = NULL, 
  map_region_panel_custom_main_text = NULL, 
  map_region_panel_width_percent = NULL, 
  map_region_panel_height_percent = NULL, 
  map_region_panel_max_width_pixels = NULL, 
  map_region_panel_max_height_pixels = NULL, 
  map_region_panel_vertical_position = NULL, 
  map_region_panel_text_color = NULL, 
  map_region_panel_font_size = NULL, 
  map_region_panel_align = NULL, 
  map_region_panel_background_color = NULL, 
  map_region_panel_background_opacity = NULL, 
  map_region_panel_padding = NULL, 
  map_region_panel_radius = NULL, 
  map_region_panel_list_type = NULL, 
  map_region_panel_list_label_weight = NULL, 
  map_region_panel_list_separator = NULL, 
  map_region_panel_shadow = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| panel_position | Position on graph: "overlay", "left", "right", "top", "bottom". |
| panel_open_duration | Time (in seconds) that the panel will remain visible. |
| panel_side_fixed | Boolean (True/False) for whether the panel is fixed to the graph (user cannot click out of the panel). |
| panel_side_default_content | Default content for the side panel (HTML). |
| panel_custom_header | Panel custom header. The text to appear in the panel. You can use ` {{column_name}} ` to add a value from your data. It must be in a selected column, but you can add columns to “Metadata” if you just want to include them for use in the panel. You can also use ` {{NAME}} ` to include the name of the current item, ` {{VALUE}} ` to include the value of the current item and ` {{SIZEBY}} ` to include the name of the column chosen to size items. Advanced users can include HTML to apply layouts, formatting, images, etc. You can also hide content based on a column name being empty using ` {{# if column_name}} `Text to display when column_name is not empty` {{/if}} `. For example: ` {{Country}} ` ` {{#if Capital}} `(Capital: ` {{Capital}} `)` {{/if}} `. |
| panel_custom_main_text | Panel custom main content. The text to appear in the panel. You can use ` {{column_name}} ` to add a value from your data. It must be in a selected column, but you can add columns to “Metadata” if you just want to include them for use in the panel. You can also use ` {{NAME}} ` to include the name of the current item, ` {{VALUE}} ` to include the value of the current item and ` {{SIZEBY}} ` to include the name of the column chosen to size items. Advanced users can include HTML to apply layouts, formatting, images, etc. You can also hide content based on a column name being empty using ` {{# if column_name}} `Text to display when column_name is not empty` {{/if}} `. For example: ` {{Country}} ` ` {{#if Capital}} `(Capital: ` {{Capital}} `)` {{/if}} `. |
| panel_width_percent | Width (%). |
| panel_height_percent | Height (%). |
| panel_max_width_pixels | Max width (px). |
| panel_max_height_pixels | Max height (px). |
| panel_vertical_position | Vertical position. Allowed values: "click", "center". Choosing "Click position" is especially useful when your visualisation is really tall, this will make sure the panel content is always on top of the element you've clicked on. |
| panel_text_color | Text color. |
| panel_font_size | Text size. |
| panel_align | Alignment. Allowed values: "start", "center", "end". |
| panel_background_color | Background color. |
| panel_background_opacity | Background opacity. Max value: 1. |
| panel_padding | Panel padding. |
| panel_radius | Corner radius of panel. |
| panel_list_type | List type. Allowed values: "table", "ul". |
| panel_list_label_weight | Label weight: "normal", "bold". |
| panel_list_separator | List separator. Allowed values: ":", "-", (empty space), `"<br />"` |
| panel_shadow | Panel shadow. Boolean (True/False). |
| map_point_panel_position | Position on graph: "overlay", "left", "right", "top", "bottom". |
| map_point_panel_open_duration | Time (in seconds) that the panel will remain visible. |
| map_point_panel_side_fixed | Boolean (True/False) for whether the panel is fixed to the graph (user cannot click out of the panel). |
| map_point_panel_side_default_content | Default content for the side panel (HTML). |
| map_point_panel_custom_header | Panel custom header. The text to appear in the panel. You can use ` {{column_name}} ` to add a value from your data. It must be in a selected column, but you can add columns to “Metadata” if you just want to include them for use in the panel. You can also use ` {{NAME}} ` to include the name of the current item, ` {{VALUE}} ` to include the value of the current item and ` {{SIZEBY}} ` to include the name of the column chosen to size items. Advanced users can include HTML to apply layouts, formatting, images, etc. You can also hide content based on a column name being empty using ` {{# if column_name}} `Text to display when column_name is not empty` {{/if}} `. For example: ` {{Country}} ` ` {{#if Capital}} `(Capital: ` {{Capital}} `)` {{/if}} `. |
| map_point_panel_custom_main_text | Panel custom main content. The text to appear in the panel. You can use ` {{column_name}} ` to add a value from your data. It must be in a selected column, but you can add columns to “Metadata” if you just want to include them for use in the panel. You can also use ` {{NAME}} ` to include the name of the current item, ` {{VALUE}} ` to include the value of the current item and ` {{SIZEBY}} ` to include the name of the column chosen to size items. Advanced users can include HTML to apply layouts, formatting, images, etc. You can also hide content based on a column name being empty using ` {{# if column_name}} `Text to display when column_name is not empty` {{/if}} `. For example: ` {{Country}} ` ` {{#if Capital}} `(Capital: ` {{Capital}} `)` {{/if}} `. |
| map_point_panel_width_percent | Width (%). |
| map_point_panel_height_percent | Height (%). |
| map_point_panel_max_width_pixels | Max width (px). |
| map_point_panel_max_height_pixels | Max height (px). |
| map_point_panel_vertical_position | Vertical position. Allowed values: "click", "center". Choosing "Click position" is especially useful when your visualisation is really tall, this will make sure the panel content is always on top of the element you've clicked on. |
| map_point_panel_text_color | Text color. |
| map_point_panel_font_size | Text size. |
| map_point_panel_align | Alignment. Allowed values: "start", "center", "end". |
| map_point_panel_background_color | Background color. |
| map_point_panel_background_opacity | Background opacity. Max value: 1. |
| map_point_panel_padding | Panel padding. |
| map_point_panel_radius | Corner radius of panel. |
| map_point_panel_list_type | List type. Allowed values: "table", "ul". |
| map_point_panel_list_label_weight | Label weight: "normal", "bold". |
| map_point_panel_list_separator | List separator. Allowed values: ":", "-", (empty space), `"<br />"` |
| map_point_panel_shadow | Panel shadow. Boolean (True/False). |
| map_region_panel_position | Position on graph: "overlay", "left", "right", "top", "bottom". |
| map_region_panel_open_duration | Time (in seconds) that the panel will remain visible. |
| map_region_panel_side_fixed | Boolean (True/False) for whether the panel is fixed to the graph (user cannot click out of the panel). |
| map_region_panel_side_default_content | Default content for the side panel (HTML). |
| map_region_panel_custom_header | Panel custom header. The text to appear in the panel. You can use ` {{column_name}} ` to add a value from your data. It must be in a selected column, but you can add columns to “Metadata” if you just want to include them for use in the panel. You can also use ` {{NAME}} ` to include the name of the current item, ` {{VALUE}} ` to include the value of the current item and ` {{SIZEBY}} ` to include the name of the column chosen to size items. Advanced users can include HTML to apply layouts, formatting, images, etc. You can also hide content based on a column name being empty using ` {{# if column_name}} `Text to display when column_name is not empty` {{/if}} `. For example: ` {{Country}} ` ` {{#if Capital}} `(Capital: ` {{Capital}} `)` {{/if}} `. |
| map_region_panel_custom_main_text | Panel custom main content. The text to appear in the panel. You can use ` {{column_name}} ` to add a value from your data. It must be in a selected column, but you can add columns to “Metadata” if you just want to include them for use in the panel. You can also use ` {{NAME}} ` to include the name of the current item, ` {{VALUE}} ` to include the value of the current item and ` {{SIZEBY}} ` to include the name of the column chosen to size items. Advanced users can include HTML to apply layouts, formatting, images, etc. You can also hide content based on a column name being empty using ` {{# if column_name}} `Text to display when column_name is not empty` {{/if}} `. For example: ` {{Country}} ` ` {{#if Capital}} `(Capital: ` {{Capital}} `)` {{/if}} `. |
| map_region_panel_width_percent | Width (%). |
| map_region_panel_height_percent | Height (%). |
| map_region_panel_max_width_pixels | Max width (px). |
| map_region_panel_max_height_pixels | Max height (px). |
| map_region_panel_vertical_position | Vertical position. Allowed values: "click", "center". Choosing "Click position" is especially useful when your visualisation is really tall, this will make sure the panel content is always on top of the element you've clicked on. |
| map_region_panel_text_color | Text color. |
| map_region_panel_font_size | Text size. |
| map_region_panel_align | Alignment. Allowed values: "start", "center", "end". |
| map_region_panel_background_color | Background color. |
| map_region_panel_background_opacity | Background opacity. Max value: 1. |
| map_region_panel_padding | Panel padding. |
| map_region_panel_radius | Corner radius of panel. |
| map_region_panel_list_type | List type. Allowed values: "table", "ul". |
| map_region_panel_list_label_weight | Label weight: "normal", "bold". |
| map_region_panel_list_separator | List separator. Allowed values: ":", "-", (empty space), `"<br />"` |
| map_region_panel_shadow | Panel shadow. Boolean (True/False). |







