---
title: "Format numbers along axes and within tooltips in Flourish"
---

*R/chart.R*

## chart_number_date_format

## Description
 Format numbers along axes and within tooltips in Flourish 


## Usage
```r
 
chart_number_date_format( 
  ., 
  x_axis_prefix = NULL, 
  x_axis_suffix = NULL, 
  x_axis_n_decimals = NULL, 
  x_axis_negative_sign = NULL, 
  x_axis_strip_zeros = NULL, 
  x_axis_strip_separator = NULL, 
  x_axis_transform_operation = NULL, 
  x_axis_multiply_divide_constant = NULL, 
  x_axis_exponentiate_constant = NULL, 
  x_axis_prop = NULL, 
  y_axis_prefix = NULL, 
  y_axis_suffix = NULL, 
  y_axis_n_decimals = NULL, 
  y_axis_negative_sign = NULL, 
  y_axis_strip_zeros = NULL, 
  y_axis_strip_separator = NULL, 
  y_axis_transform_operation = NULL, 
  y_axis_multiply_divide_constant = NULL, 
  y_axis_exponentiate_constant = NULL, 
  y_axis_prop = NULL, 
  secondary_y_axis_prefix = NULL, 
  secondary_y_axis_suffix = NULL, 
  secondary_y_axis_n_decimals = NULL, 
  secondary_y_axis_negative_sign = NULL, 
  secondary_y_axis_strip_zeros = NULL, 
  secondary_y_axis_strip_separator = NULL, 
  secondary_y_axis_transform_operation = NULL, 
  secondary_y_axis_multiply_divide_constant = NULL, 
  secondary_y_axis_exponentiate_constant = NULL, 
  secondary_y_axis_prop = NULL, 
  number_prefix = NULL, 
  number_suffix = NULL, 
  number_n_decimals = NULL, 
  number_negative_sign = NULL, 
  number_strip_zeros = NULL, 
  number_strip_separator = NULL, 
  number_transform_operation = NULL, 
  number_multiply_divide_constant = NULL, 
  number_exponentiate_constant = NULL, 
  number_prop = NULL, 
  legend_prefix = NULL, 
  legend_suffix = NULL, 
  legend_n_decimals = NULL, 
  legend_negative_sign = NULL, 
  legend_strip_zeros = NULL, 
  legend_strip_separator = NULL, 
  legend_transform_operation = NULL, 
  legend_multiply_divide_constant = NULL, 
  legend_exponentiate_constant = NULL, 
  map_region_prefix = NULL, 
  map_region_suffix = NULL, 
  map_region_n_decimals = NULL, 
  map_region_negative_sign = NULL, 
  map_region_strip_zeros = NULL, 
  map_region_strip_separator = NULL, 
  map_region_transform_operation = NULL, 
  map_region_multiply_divide_constant = NULL, 
  map_region_exponentiate_constant = NULL, 
  color_transform_operation = NULL, 
  color_multiply_divide_constant = NULL, 
  color_exponentiate_constant = NULL, 
  map_region_prop = NULL, 
  map_point_prefix = NULL, 
  map_point_suffix = NULL, 
  map_point_n_decimals = NULL, 
  map_point_negative_sign = NULL, 
  map_point_strip_zeros = NULL, 
  map_point_strip_separator = NULL, 
  map_point_transform_operation = NULL, 
  map_point_multiply_divide_constant = NULL, 
  map_point_exponentiate_constant = NULL, 
  map_point_prop = NULL, 
  localization_input_decimal_string_separator = NULL, 
  localization_input_decimal_separator = NULL, 
  localization_output_separators = NULL, 
  label_data_type = NULL, 
  datetime_input_format = NULL, 
  x_axis_date_format = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| x_axis_prefix | Prefix. Text to place in front of number. |
| x_axis_suffix | Suffix. Text to place after the number. |
| x_axis_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| x_axis_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| x_axis_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| x_axis_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| x_axis_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| x_axis_multiply_divide_constant | Constant number to multiply/divide by. |
| x_axis_exponentiate_constant | Constant number to exponentiate by. |
| x_axis_prop | Show % values. Sets whether the raw numbers from the data sheet or the computed percent values from the chart show in labels and popups. |
| y_axis_prefix | Prefix. Text to place in front of number. |
| y_axis_suffix | Suffix. Text to place after the number. |
| y_axis_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| y_axis_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| y_axis_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| y_axis_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| y_axis_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| y_axis_multiply_divide_constant | Constant number to multiply/divide by. |
| y_axis_exponentiate_constant | Constant number to exponentiate by. |
| y_axis_prop | Show % values. Sets whether the raw numbers from the data sheet or the computed percent values from the chart show in labels and popups. |
| secondary_y_axis_prefix | Prefix. Text to place in front of number. |
| secondary_y_axis_suffix | Suffix. Text to place after the number. |
| secondary_y_axis_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| secondary_y_axis_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| secondary_y_axis_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| secondary_y_axis_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| secondary_y_axis_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| secondary_y_axis_multiply_divide_constant | Constant number to multiply/divide by. |
| secondary_y_axis_exponentiate_constant | Constant number to exponentiate by. |
| secondary_y_axis_prop | Show % values. Sets whether the raw numbers from the data sheet or the computed percent values from the chart show in labels and popups. |
| number_prefix | Prefix. Text to place in front of number. |
| number_suffix | Suffix. Text to place after the number. |
| number_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| number_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| number_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| number_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| number_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| number_multiply_divide_constant | Constant number to multiply/divide by. |
| number_exponentiate_constant | Constant number to exponentiate by. |
| number_prop | Show % values. Sets whether the raw numbers from the data sheet or the computed percent values from the chart show in labels and popups. |
| legend_prefix | Prefix. Text to place in front of number. |
| legend_suffix | Suffix. Text to place after the number. |
| legend_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| legend_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| legend_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| legend_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| legend_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| legend_multiply_divide_constant | Constant number to multiply/divide by. |
| legend_exponentiate_constant | Constant number to exponentiate by. |
| map_region_prefix | Prefix. Text to place in front of number. |
| map_region_suffix | Suffix. Text to place after the number. |
| map_region_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| map_region_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| map_region_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| map_region_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| map_region_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| map_region_multiply_divide_constant | Constant number to multiply/divide by. |
| map_region_exponentiate_constant | Constant number to exponentiate by. |
| color_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| color_multiply_divide_constant | Constant number to multiply/divide by. |
| color_exponentiate_constant | Constant number to exponentiate by. |
| map_region_prop | Show % values. Sets whether the raw numbers from the data sheet or the computed percent values from the chart show in labels and popups. |
| map_point_prefix | Prefix. Text to place in front of number. |
| map_point_suffix | Suffix. Text to place after the number. |
| map_point_n_decimals | Decimal places. Use negative integers to round to positive powers of ten (eg -2 rounds to the nearest 100). Min: -10. Max: 10. |
| map_point_negative_sign | Styling of negative numbers. Allowed values:  "-$nk" (-$100k), "$-nk" ($-100k), "($nk)" (($100k)), "$(n)k" ($(100)k), "none" ($100k). |
| map_point_strip_zeros | Remove trailing zeros. Boolean (True/False). |
| map_point_strip_separator | Hide thousands separator below 10,000. Turn off if you want four-digit numbers to include a separator, e.. “1,234” rather than “1234”. |
| map_point_transform_operation | Allowed values: "multiply" (Multiply by), "divide" (Divide by), "exponentiate" (x10 to the power of) |
| map_point_multiply_divide_constant | Constant number to multiply/divide by. |
| map_point_exponentiate_constant | Constant number to exponentiate by. |
| map_point_prop | Show % values. Sets whether the raw numbers from the data sheet or the computed percent values from the chart show in labels and popups. |
| localization_input_decimal_string_separator | Decimal separator in data sheet. Used for interpreting your data. Only change if data is not displaying on the chart as expected. |
| localization_input_decimal_separator | Allowed values: ".", ",". |
| localization_output_separators | Number format to display. How the numbers should appear on chart labels. Allowed values: ",." (12,235.67); ".," (12.345,67); "." (12235.67); "," (12345,67);  " ." (12 235.67);  " ," (12 345,67). |
| label_data_type | Data type. String: "auto", "number", "datetime", "categorical" |
| datetime_input_format | Format in data sheet. The date/time format in the data sheet. Leave as “Auto” for Flourish to make a best guess. If it isn’t in the list, you can enter a custom format using d3-time-format syntax. See npmjs.com/package/d3-time-format for details. |
| x_axis_date_format | Display format, i.e. "%B %d" == January 28. The date/time format to show in the graphic. If it isn’t in the list, you can enter a custom format using d3-time-format syntax. See npmjs.com/package/d3-time-format for details. |







