---
title: "Set survey details"
---

*R/details.R*

## set_survey_details

## Description
 Set survey details 


## Usage
```r
 
set_survey_details( 
  ., 
  dot_fill = NULL, 
  dot_opacity = NULL, 
  dot_opacity_unhighlighted = NULL, 
  dot_shape = NULL, 
  dot_sides = NULL, 
  dot_label = NULL, 
  dot_label_color = NULL, 
  dot_label_bold = NULL, 
  dot_label_minimum = NULL, 
  dot_label_auto_size = NULL, 
  dot_label_fixed = NULL, 
  dot_label_scale = NULL, 
  dot_label_size_value = NULL, 
  all_group_label = NULL, 
  include_grouped_questions_on_shade_menu = NULL, 
  include_grouped_questions_on_compare_menu = NULL, 
  order_groups_by_size = NULL, 
  group_colors = NULL, 
  exclusions = NULL, 
  exclude_blanks = NULL, 
  bundle_small_groups = NULL, 
  small_groups_threshold = NULL, 
  small_groups_other_label = NULL, 
  label_mode = NULL, 
  label_tight_fit = NULL, 
  label_color = NULL, 
  label_min_font_size = NULL, 
  label_max_font_size = NULL, 
  label_group_padding_lines = NULL, 
  label_shadow_size = NULL, 
  label_shadow_color = NULL, 
  label_group_count = NULL, 
  label_group_percent = NULL, 
  label_group_percent_decimals = NULL, 
  always_show_x_label = NULL, 
  show_xy_axis_labels_when_comparing = NULL, 
  compare_y_axis_width = NULL, 
  compare_x_axis_height = NULL, 
  chart_height_mode = NULL, 
  chart_aspect_ratio_wide = NULL, 
  chart_aspect_ratio_narrow = NULL, 
  map_opacity_map_mode = NULL, 
  map_opacity_non_map_mode = NULL, 
  map_max_group_size = NULL, 
  map_dimensions = NULL, 
  map_aspect_ratio = NULL, 
  map_region = NULL, 
  map_region_url = NULL, 
  minimum_longitude = NULL, 
  maximum_longitude = NULL, 
  minimum_latitude = NULL, 
  maximum_latitude = NULL, 
  zoom_on_double_click = NULL, 
  zoom_on_mousewheel = NULL, 
  transition_duration = NULL, 
  transition_stagger = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| dot_fill | Default color. If left blank, will use the first color of the color palette |
| dot_opacity | Opacity. Max: 1. |
| dot_opacity_unhighlighted | Unhighlighted opacity. Max: 1 |
| dot_shape | Shape. Allowed values: "circle", "square", "polygon" |
| dot_sides | Sides. Min: 3; Max: 16. |
| dot_label | Default label or emoji.  A label or emoji to show on each dot. Overriden by any label specified using the Label column setting. |
| dot_label_color | Color |
| dot_label_bold | Boolean. Bold font. |
| dot_label_minimum | minimum size to display. |
| dot_label_auto_size | Sizing mode. Boolean. |
| dot_label_fixed | Size in %. Specifies font size across graphic as % of dot height. |
| dot_label_scale | Scale. Scale label up or down from default size. |
| dot_label_size_value | Boolean. Show numerical value when sizing dots |
| all_group_label | Name for "all" group |
| include_grouped_questions_on_shade_menu | Boolean. Include grouped questions on shading menu. |
| include_grouped_questions_on_compare_menu | Boolean. Include grouped questions on compare menu. |
| order_groups_by_size | Boolean. Order groups by size. |
| group_colors | Boolean. Arrange groups by color. If selected, dots of the same color are grouped together; if not the dots are placed in spreadsheet order. |
| exclusions | Exclude groups with following names. |
| exclude_blanks | Exclude groups with blank names |
| bundle_small_groups | Boolean. Bundle small groups |
| small_groups_threshold | Small groups threshold number. |
| small_groups_other_label | Label for small groups. |
| label_mode | Label position. Allowed values: "atop", "around", "above" |
| label_tight_fit | Position close to group. Boolean. |
| label_color | Text color |
| label_min_font_size | minimum font size. In pixels; the actual font size in any view is set automatically between the minimum and max |
| label_max_font_size | maximum font size |
| label_group_padding_lines | Space for labels. The amount of space to leave above the groups, specified in lines of text |
| label_shadow_size | Size as a % of font size. Max: 100 |
| label_shadow_color | Color |
| label_group_count | Boolean. Show number of dots in group. Adds the number in brackets after the main label; ignored in chart, map and compare modes |
| label_group_percent | Boolean. Show group size as % of visible dots. Adds to the labels group size as a in brackets after the main label; ignored in chart, map and compare modes, and when showing a grouped question |
| label_group_percent_decimals | Decimal places on percentage labels |
| always_show_x_label | Boolean. Show X label when not comparing. Show the groups label at the bottom when not comparing two metrics. |
| show_xy_axis_labels_when_comparing | Boolean. Show X/Y labels when comparing. Show groups labels on both axes when comparing two metrics |
| compare_y_axis_width | Y axis width |
| compare_x_axis_height | X axis height |
| chart_height_mode | Height mode. How the graphic height will be set when embedded with the responsive script embed without a specified height. Allowed values: "auto", "aspect ratio". |
| chart_aspect_ratio_wide | Desktop. The chart aspect ratio on screens 640 pixels wide and higher (1 for square - a smaller value means a bigger height). Min: 0.1; Max: 10. |
| chart_aspect_ratio_narrow | Mobile. The chart aspect ratio on screens narrower than 640 pixels (1 for square - a smaller value means a bigger height). Min: 0.1; Max: 10. |
| map_opacity_map_mode | Map opacity (in map mode). Max: 1 |
| map_opacity_non_map_mode | Map opacity (in other modes). Max: 1 |
| map_max_group_size | maximum group size in map view. In relative units. Min: 0.1 |
| map_dimensions | Map dimensions. Allowed values: "auto", "aspect_ratio" |
| map_aspect_ratio | Map aspect ratio. Aspect ratio of the map. 1 will make the map square. Min: 0.1 |
| map_region | Region. Allowed values: "world", "usa", "europe", "custom" |
| map_region_url | URL to equirectangular projection of map. |
| minimum_longitude | Minimum longitude. Min: -180. Max: 180 |
| maximum_longitude | Maximum longitude. Min: -180. Max: 180 |
| minimum_latitude | Minimum latitude. Min: -90. Max: 90 |
| maximum_latitude | Maximum latitude. Min: -90. Max: 90 |
| zoom_on_double_click | Zoom on double click. Boolean (True/False). |
| zoom_on_mousewheel | Zoom on pinch/mousewheel. Boolean (True/False). |
| transition_duration | Duration. Time in milliseconds of each dot's animation |
| transition_stagger | Stagger. The spread of time over which the dots start animating |






## See Also
 Other Flourish quizzes, surveys, and tables:  `bind_quiz_data()`, `bind_survey_data()`, `bind_table_data()`, `set_quiz_details()`, `set_table_details()` 

