---
title: "Set table details"
---

*R/details.R*

## set_table_details

## Description
 Set table details 


## Usage
```r
 
set_table_details( 
  ., 
  table_min_width = NULL, 
  table_border_width = NULL, 
  table_border_color = NULL, 
  sorting_enabled = NULL, 
  sorting_custom_columns = NULL, 
  pagination_amount = NULL, 
  markdown_enabled = NULL, 
  cell_height = NULL, 
  cell_padding_vertical = NULL, 
  cell_padding_horizontal = NULL, 
  cell_vertical_alignment = NULL, 
  cell_horizontal_alignment = NULL, 
  cell_wrap = NULL, 
  cell_fill_1 = NULL, 
  cell_fill_2 = NULL, 
  cell_fill_direction = NULL, 
  cell_fill_custom_enabled = NULL, 
  cell_fill_custom = NULL, 
  cell_fill_margin_vertical = NULL, 
  cell_fill_margin_horizontal = NULL, 
  cell_border_color = NULL, 
  cell_border_width = NULL, 
  cell_border_style = NULL, 
  cell_font_color = NULL, 
  cell_link_color = NULL, 
  cell_font_size = NULL, 
  cell_font_size_custom = NULL, 
  column_width_mode = NULL, 
  column_widths = NULL, 
  header_font_weight = NULL, 
  header_fill = NULL, 
  header_font_color = NULL, 
  header_underline_sorting = NULL, 
  header_style_default = NULL, 
  header_height = NULL, 
  header_padding = NULL, 
  header_horizontal_alignment = NULL, 
  header_font_default = NULL, 
  header_font_size = NULL, 
  header_border_default = NULL, 
  header_border_color = NULL, 
  header_border_width = NULL, 
  header_border_style = NULL, 
  cell_image_height = NULL, 
  cell_image_radius = NULL, 
  bar_minichart_columns = NULL, 
  bar_minichart_columns_new_column_name = NULL, 
  bar_minichart_columns_bars_or_columns = NULL, 
  bar_minichart_columns_height = NULL, 
  bar_minichart_columns_width = NULL, 
  bar_minichart_columns_column_padding = NULL, 
  bar_minichart_columns_proportional = NULL, 
  bar_minichart_columns_same_scale = NULL, 
  bar_minichart_columns_zero_line = NULL, 
  bar_minichart_columns_zero_line_color = NULL, 
  bar_minichart_columns_custom_color = NULL, 
  bar_minichart_columns_custom_value = NULL, 
  bar_minichart_columns_labels = NULL, 
  bar_minichart_columns_label_size = NULL, 
  line_minichart_columns = NULL, 
  line_minichart_columns_new_column_name = NULL, 
  line_minichart_columns_width = NULL, 
  line_minichart_columns_height = NULL, 
  line_minichart_columns_color = NULL, 
  line_minichart_columns_area = NULL, 
  line_minichart_columns_minimum = NULL, 
  line_minichart_columns_maximum = NULL, 
  mobile_view = NULL, 
  mobile_breakpoint = NULL, 
  mobile_cell_font_size = NULL, 
  mobile_cell_font_size_custom = NULL, 
  mobile_pagination_amount = NULL, 
  search_mode = NULL, 
  search_width = NULL, 
  search_background_color = NULL, 
  search_text_color = NULL, 
  search_placeholder = NULL, 
  no_results_text = NULL, 
  search_hide_table = NULL, 
  search_hide_published = NULL, 
  search_columns = NULL, 
  search_columns_custom = NULL, 
  search_resize = NULL, 
  search_dropdown = NULL, 
  search_dropdown_persistent = NULL, 
  search_val = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| table_min_width | number minimum width. Min: 100 |
| table_border_width | number Border. |
| table_border_color | color Border color. |
| sorting_enabled | string Sortable columns. Determines whether a viewer can sort the table by clicking on the column headers. Allowed values: all, none, custom |
| sorting_custom_columns | text Columns to make sortable. Write each column name you want to make sortable on a new line |
| pagination_amount | number Rows per page. If you don't want pagination, set this number to a value higher than the length of your data. Max: 5000 |
| markdown_enabled | boolean Cell text styling. Enables Markdown style parsing for your cells. For example for **italic**, **bold** text. Go to template guide for full documentation. Allowed values: true (On), false (Off) |
| cell_height | number minimum height. |
| cell_padding_vertical | number Padding vertical. |
| cell_padding_horizontal | number Padding horizontal. |
| cell_vertical_alignment | string Vertical alignment. Allowed values: top, center, bottom |
| cell_horizontal_alignment | string Horizontal alignment. Allowed values: start, center, end |
| cell_wrap | boolean Wrap text in cell. |
| cell_fill_1 | color Main color. |
| cell_fill_2 | color Stripe color. |
| cell_fill_direction | string Stripe direction. Allowed values: horizontal, vertical |
| cell_fill_custom_enabled | boolean Color cells based on content. |
| cell_fill_custom | text Cells to color. Color cells based on their content. Use the format “background-color : cell-text : column_name” or “background-color/text-color: cell-text : column_name”. It's also possible to leave out the column name, if you want to target all the cells in the table. Eg: c("#0000dd/#ffffff : Alabama", "#ffffff/#dddddd : n/a : Capital") |
| cell_fill_margin_vertical | number Vertical margin. |
| cell_fill_margin_horizontal | number Horizontal margin. |
| cell_border_color | color Color. |
| cell_border_width | number Thickness. |
| cell_border_style | string Style. Allowed values: solid, dashed, dotted |
| cell_font_color | color Color. |
| cell_link_color | color Link color. |
| cell_font_size | string Size. Allowed values: "1", "1.25", "1.5", "custom" |
| cell_font_size_custom | number Custom. Specify a custom responsive font size. Best results will be with values between 1.2 and 3 |
| column_width_mode | string Allowed values: auto, equal, fixed |
| column_widths | string Column widths. A comma separated vector of column widths. The first column will be the first number in the list. You can use "px" to set fixed widths or "%" to use percentage of total width. (e.g. 200px,200px,25%) |
| header_font_weight | string Text weight. Allowed values: bold, normal |
| header_fill | color Background. |
| header_font_color | color Color. |
| header_underline_sorting | boolean Underline sorting header. |
| header_style_default | boolean Allowed values: true (Inherit styles), false (Custom) |
| header_height | number Height. |
| header_padding | number Padding. |
| header_horizontal_alignment | string Horizontal alignment. Allowed values: start, center, end |
| header_font_default | boolean Allowed values: true (Inherit styles), false (Custom) |
| header_font_size | number Size. |
| header_border_default | boolean Allowed values: true (Inherit styles), false (Custom) |
| header_border_color | color Color. |
| header_border_width | number Thickness. |
| header_border_style | string Style. Allowed values: solid, dashed, dotted |
| cell_image_height | number Height. as a percentage of the cell height. Max: 200 |
| cell_image_radius | number Rounded corners. Sets the radius of the corner roundness (in %). A value of 50 means your image will show as a circle. Max: 50 |
| bar_minichart_columns | text A vector of columns that should be part of the bar chart |
| bar_minichart_columns_new_column_name | string New column name. |
| bar_minichart_columns_bars_or_columns | Bar type. Allowed values: bars (Horizontal), columns (Vertical) |
| bar_minichart_columns_height | number maximum height. |
| bar_minichart_columns_width | number Width. |
| bar_minichart_columns_column_padding | number Padding. |
| bar_minichart_columns_proportional | boolean Mode. Display data in a proportional bar chart or a standard stacked bar chart with a fixed minimum and max, e.g. for negative numbers Allowed values: false (Stacked normal), true (Stacked %) |
| bar_minichart_columns_same_scale | boolean Consistent scale. If enabled, all the bar charts in the table will use the same X scale |
| bar_minichart_columns_zero_line | boolean Show zero line. |
| bar_minichart_columns_zero_line_color | color Zero line color. |
| bar_minichart_columns_custom_color | color Custom colors (vector). |
| bar_minichart_columns_custom_value | string Custom values to match colors (vector). |
| bar_minichart_columns_labels | string Labels. Allowed values: none, popup, inline |
| bar_minichart_columns_label_size | number Inline label size. |
| line_minichart_columns | text A vector of columns should be part of the line chart |
| line_minichart_columns_new_column_name | string New column name. |
| line_minichart_columns_width | number Width. |
| line_minichart_columns_height | number maximum height. |
| line_minichart_columns_color | color Color. |
| line_minichart_columns_area | boolean Area chart. Allowed values: true (On), false (Off) |
| line_minichart_columns_minimum | number minimum value. |
| line_minichart_columns_maximum | number maximum value. |
| mobile_view | boolean Mobile view. Allowed values: false (Table (scrollbars)), true (Blocks) |
| mobile_breakpoint | number Mobile breakpoint width. Min: 10 |
| mobile_cell_font_size | string Text size. Allowed values: "1", "1.25", "1.5", "custom" (...) |
| mobile_cell_font_size_custom | number Custom. Specify a custom responsive font size. Best results will be with values between 1.2 and 3 |
| mobile_pagination_amount | number Rows per page. If you don't want pagination, set this number to a value higher than the length of your data. Min: 1 |
| search_mode | string Search mode. Anywhere: Search for the specified text anywhere in the cell Start: Search for the specified text at the beginning of the cell Whole: Search for the exact specified text in the cell Allowed values: anywhere (Anywhere), start (Start), whole (Whole) |
| search_width | number Width. Width of search container. Min: 4 |
| search_background_color | color Background. |
| search_text_color | color Text color. |
| search_placeholder | string Placeholder text. |
| no_results_text | string Text when no results. |
| search_hide_table | boolean Hide table before search. |
| search_hide_published | boolean Hide search when published. Keeps the search box visible in the editor (e.g. for filtering in a story) but hides it in the published visualization or story. |
| search_columns | string "All", "First", "Custom" |
| search_columns_custom | text Columns to search. Choose which columns you want to search through. You might want to narrow this down with big datasets to speed it up. |
| search_resize | boolean Resize table after searching. Allowed values: true (Enabled), false (Disabled) |
| search_dropdown | boolean Allowed values: true (Enabled), false (Disabled) |
| search_dropdown_persistent | boolean Always show dropdown suggestions. |
| search_val | string Search value. The current string value of the search box |


## Section

## Table

 NA 

## Cell styles

 NA 

## Mini bar/column charts (sparklines)

 NA 

## Mini line charts (sparklines)

 NA 

## Mobile view

 NA 

## Search

 NA 




## See Also
 Other Flourish quizzes, surveys, and tables:  `bind_quiz_data()`, `bind_survey_data()`, `bind_table_data()`, `set_quiz_details()`, `set_survey_details()` 

