---
title: "Set photoslider details"
---

*R/details.R*

## set_photo_slider_details

## Description
 Set photoslider details 


## Usage
```r
 
set_photo_slider_details( 
  ., 
  mode = NULL, 
  spotlight_size = NULL, 
  spotlight_blur = NULL, 
  spotlight_speed = NULL, 
  photo_1_big = NULL, 
  has_photo_1_small = NULL, 
  photo_1_small = NULL, 
  photo_2_big = NULL, 
  has_photo_2_small = NULL, 
  photo_2_small = NULL, 
  slider_radius = NULL, 
  slider_fill_type = NULL, 
  slider_fill_image = NULL, 
  slider_fill_overlay = NULL, 
  slider_fill_standalone = NULL, 
  slider_line_thickness = NULL, 
  slider_line_color = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| mode | Before/after mode. Allowed values: slide, fade, spotlight |
| spotlight_size | Spotlight size. |
| spotlight_blur | Spotlight blur. Max: 100 |
| spotlight_speed | Spotlight animation. Time it takes to animate from one spotlight position to another in the story player |
| photo_1_big | Photo URL |
| has_photo_1_small | Boolean (True/False). Add smaller version for mobile. (Optional) Mobile versions will be loaded quicker on smaller screens |
| photo_1_small | Photo URL. Photo 1 (mobile version). This picture should be roughly 500px wide |
| photo_2_big | Photo URL |
| has_photo_2_small | Boolean (True/False). Add smaller version for mobile. (Optional) Mobile versions will be loaded quicker on smaller screens |
| photo_2_small | Photo URL. Photo 2 (mobile version). This picture should be roughly 500px wide. |
| slider_radius | number Size |
| slider_fill_type | Type. Allowed values:"color","image" |
| slider_fill_image | Image URL |
| slider_fill_overlay | Fill. |
| slider_fill_standalone | Fill (outside picture). |
| slider_line_thickness | Slider line thickness. |
| slider_line_color | Slider line color. |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

