---
title: "Set card details"
---

*R/details.R*

## set_card_details

## Description
 Set card details 


## Usage
```r
 
set_card_details( 
  ., 
  mode = NULL, 
  carousel_channel_background_color = NULL, 
  carousel_bar_background_color = NULL, 
  carousel_channel_height = NULL, 
  autoplay_enabled = NULL, 
  autoplay_duration = NULL, 
  autoplay_loop = NULL, 
  autoplay_pause_when = NULL, 
  autoplay_button_visible = NULL, 
  autoplay_button_position = NULL, 
  autoplay_button_size = NULL, 
  autoplay_button_background = NULL, 
  autoplay_button_opacity = NULL, 
  autoplay_button_color = NULL, 
  card_layout = NULL, 
  card_order = NULL, 
  card_width_portrait = NULL, 
  card_width_landscape = NULL, 
  card_width_stretch = NULL, 
  card_width_stretch_percent = NULL, 
  card_padding_top = NULL, 
  card_padding_right = NULL, 
  card_padding_bottom = NULL, 
  card_padding_left = NULL, 
  card_horizontal_margin = NULL, 
  card_vertical_margin = NULL, 
  card_border_color = NULL, 
  card_border_width = NULL, 
  card_shape = NULL, 
  card_radius = NULL, 
  card_shadow = NULL, 
  card_shadow_color = NULL, 
  card_shadow_blur = NULL, 
  template_customise = NULL, 
  template_simple_custom = NULL, 
  content_vertical_align = NULL, 
  content_horizontal_padding = NULL, 
  title_color = NULL, 
  title_fontsize = NULL, 
  title_weight = NULL, 
  title_opacity = NULL, 
  title_space_above = NULL, 
  title_space_below = NULL, 
  title_lineheight = NULL, 
  title_minheight = NULL, 
  title_align = NULL, 
  subtitle_color = NULL, 
  subtitle_fontsize = NULL, 
  subtitle_weight = NULL, 
  subtitle_opacity = NULL, 
  subtitle_space_above = NULL, 
  subtitle_space_below = NULL, 
  subtitle_lineheight = NULL, 
  subtitle_minheight = NULL, 
  subtitle_align = NULL, 
  text_color = NULL, 
  text_fontsize = NULL, 
  text_weight = NULL, 
  text_opacity = NULL, 
  text_space_above = NULL, 
  text_space_below = NULL, 
  text_space_between = NULL, 
  text_lineheight = NULL, 
  text_minheight = NULL, 
  text_align = NULL, 
  text_column_names = NULL, 
  text_column_separator = NULL, 
  text_column_weight = NULL, 
  text_column_separator_custom = NULL, 
  image_width_portrait = NULL, 
  image_width_landscape = NULL, 
  image_aspect_ratio = NULL, 
  image_sizing = NULL, 
  image_horizontal_margin = NULL, 
  image_vertical_margin = NULL, 
  card_space_between = NULL, 
  image_border_color = NULL, 
  image_border_width = NULL, 
  image_shape = NULL, 
  image_radius = NULL, 
  image_opacity = NULL, 
  image_contrast = NULL, 
  image_brightness = NULL, 
  image_blend_mode = NULL, 
  image_blackwhite = NULL, 
  image_missing = NULL, 
  image_missing_icon = NULL, 
  card_background_mode = NULL, 
  card_background_color = NULL, 
  card_background_mode_category = NULL, 
  card_background_color_category = NULL, 
  image_background_mode = NULL, 
  image_background_color = NULL, 
  image_background_mode_category = NULL, 
  image_background_color_category = NULL, 
  audio_click = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| mode | View mode. Allowed values: "grid", "carousel" |
| carousel_channel_background_color | Channel color. |
| carousel_bar_background_color | Bar color. |
| carousel_channel_height | Channel height. Min: 1 |
| autoplay_enabled | Boolean (True/False) |
| autoplay_duration | Duration. |
| autoplay_loop | Boolean (True/False) |
| autoplay_pause_when | Pause on interaction. Allowed values: "never", "hover", "popup ", "hover_popup" |
| autoplay_button_visible | Boolean (True/False) |
| autoplay_button_position | Position. Allowed values: "top_left", "top_right", "bottom_left", "bottom_right" |
| autoplay_button_size | Size. |
| autoplay_button_background | Background color |
| autoplay_button_opacity | Opacity. |
| autoplay_button_color | Color. |
| card_layout | Card layout. Allowed values: "portrait", "landscape", "absolute" |
| card_order | Card structure. Allowed values: "stack-default" (Image above text), "stack-2", "stack-3", "stack-4" |
| card_width_portrait | Width. |
| card_width_landscape | Width. |
| card_width_stretch | Boolean (True/False). Stretch cards to fill. |
| card_width_stretch_percent | Percent stretch. How much the cards are allow to scale up to fill the space, in %. (When too much stretch would be required, cards are scaled down to add a column to the grid.) |
| card_padding_top | Top. |
| card_padding_right | Right. |
| card_padding_bottom | Bottom. |
| card_padding_left | Left. |
| card_horizontal_margin | Horizontal. |
| card_vertical_margin | Vertical. |
| card_border_color | Border color. |
| card_border_width | Weight. |
| card_shape | Shape. Allowed values: "circle", "square" |
| card_radius | Roundness.Max: 100 |
| card_shadow | Boolean (True/False). Shadow behind card. |
| card_shadow_color | Color. |
| card_shadow_blur | Blur. |
| template_customise | Boolean (True/False) Customise card HTML. |
| template_simple_custom | Custom HTML. Refer to columns using `{{column_name}}`. If your column name has spaces, wrap the column name in square brackets, like `{{[column name]}}`. Use handlebar syntax for conditions, etc. See handlebarsjs.com for more information. |
| content_vertical_align | Vertical position. Allowed values: center (Center), flex-start (Top), flex-end (Bottom) |
| content_horizontal_padding | Horizontal space. |
| title_color | Color. |
| title_fontsize | Font size. |
| title_weight | Allowed values: "italic", "bold", "normal". |
| title_opacity | Opacity. Max: 1 |
| title_space_above | Space above. |
| title_space_below | Space below. |
| title_lineheight | Line height. |
| title_minheight | minimum height. |
| title_align | Align. Allowed values: "left", "center", "right" |
| subtitle_color | Color. |
| subtitle_fontsize | Font size. |
| subtitle_weight | Weight. Allowed values: "italic", "normal", "bold" |
| subtitle_opacity | Opacity. Max: 1 |
| subtitle_space_above | Space above. |
| subtitle_space_below | Space below. |
| subtitle_lineheight | Line height. |
| subtitle_minheight | minimum height. |
| subtitle_align | Align. Allowed values: "left", "center", "right" |
| text_color | Color. |
| text_fontsize | Font size. |
| text_weight | Weight. Allowed values: "italic", "normal", "bold" |
| text_opacity | Opacity. Max: 1 |
| text_space_above | Space above. |
| text_space_below | Space below. |
| text_space_between | Space between. |
| text_lineheight | Line height. |
| text_minheight | minimum height. |
| text_align | Align.Allowed values: "left", "center", "right" |
| text_column_names | Boolean (True/False). Column names. To add column names before text entries. |
| text_column_separator | Column separator. Choose a separator between column names and text entries. Allowed values: ':', '-', '<br>', 'other' |
| text_column_weight | Weight. Allowed values: "bold", "normal" |
| text_column_separator_custom | string |
| image_width_portrait | Width. As a % of the card width |
| image_width_landscape | Width. As a % of the card width |
| image_aspect_ratio | Aspect ratio. As a multiplier of the image width. For example: a value of 2, means the image height is 2 times the image width |
| image_sizing | Image sizing. Allowed values: "cover" (Fill), "contain" (Fit) |
| image_horizontal_margin | Horizontal. As a % of the card width |
| image_vertical_margin | Vertical. As a % of the card width |
| card_space_between | Space between image and text. |
| image_border_color | Color. |
| image_border_width | Weight. |
| image_shape | Shape. Allowed values: circle, square |
| image_radius | Roundness. Max: 100 |
| image_opacity | Opacity. Max: 1 |
| image_contrast | Contrast. Max: 100 |
| image_brightness | Brightness. Max: 100 |
| image_blend_mode | Blend mode. Allowed values: "normal", "lighten", "darken", "overlay", "screen", "multiply" |
| image_blackwhite | Boolean (True/False). Black and white. |
| image_missing | Missing images. What to show when there is a missing image. Allowed values: "hide", "icon" |
| image_missing_icon | Missing icon URL |
| card_background_mode | Card. Allowed values: "transparent", "fixed" |
| card_background_color | Color. |
| card_background_mode_category | Card. Choose 'Data' if you want to base the color on a column in your dataset. Allowed values: "data", "transparent", "fixed" |
| card_background_color_category | Color. |
| image_background_mode | Image. Allowed values: "transparent", "fixed" |
| image_background_color | Color. |
| image_background_mode_category | Image. Choose 'Data' if you want to base the color on a column in your dataset. Allowed values: "data", "transparent", "fixed" |
| image_background_color_category | Color. |
| audio_click | Click while playing should: "replay", "stop", "pause". |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

