---
title: "Set radar chart details"
---

*R/details.R*

## set_radar_details

## Description
 Set radar chart details 


## Usage
```r
 
set_radar_details( 
  ., 
  radar_line_curve = NULL, 
  radar_line_star = NULL, 
  radar_stroke_width = NULL, 
  radar_stroke_opacity = NULL, 
  radar_fill_opacity = NULL, 
  radar_star_inner_radius = NULL, 
  facet_comparisons = NULL, 
  facet_comparison_stroke_color = NULL, 
  facet_comparison_stroke_width = NULL, 
  facet_comparison_stroke_opacity = NULL, 
  facet_comparison_fill = NULL, 
  facet_comparison_fill_opacity = NULL, 
  radial_axis_show = NULL, 
  radial_axis_x_line_color = NULL, 
  radial_axis_x_line_width = NULL, 
  radial_axis_x_tick_label_color = NULL, 
  radial_axis_x_tick_label_size = NULL, 
  radial_axis_x_tick_label_outline = NULL, 
  radial_axis_x_tick_label_weight = NULL, 
  radial_axis_y_minimum = NULL, 
  radial_axis_y_maximum = NULL, 
  radial_axis_y_tick_number = NULL, 
  radial_axis_y_line_color = NULL, 
  radial_axis_y_line_width = NULL, 
  radial_axis_y_line_dash = NULL, 
  radial_axis_y_line_dash_gap = NULL, 
  radial_axis_y_tick_label_color = NULL, 
  radial_axis_y_tick_label_size = NULL, 
  radial_axis_y_tick_label_outline = NULL, 
  radial_axis_y_tick_label_space = NULL, 
  radial_axis_y_tick_label_weight = NULL, 
  radial_axis_margin_top = NULL, 
  radial_axis_margin_right = NULL, 
  radial_axis_margin_bottom = NULL, 
  radial_axis_margin_left = NULL, 
  radial_axis_group_labels_custom_value = NULL, 
  radial_axis_group_labels_custom_angle = NULL, 
  radial_axis_group_labels_color = NULL, 
  radial_axis_group_labels_size = NULL, 
  radial_axis_group_labels_letter_spacing = NULL, 
  radial_axis_group_labels_space_above = NULL, 
  radial_axis_group_labels_space_below = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| radar_line_curve | Line curve. Allowed values: linear (Straight), cardinal (Curve) |
| radar_line_star | Line shape Allowed values: false (Ring), true (Star) |
| radar_stroke_width | Line width. |
| radar_stroke_opacity | Line opacity. Max: 1 |
| radar_fill_opacity | Fill opacity. Max: 1 |
| radar_star_inner_radius | Star inner. The star shapes inner radius, as a percent of the maximum radius. Max: 100 |
| facet_comparisons | Show comparison lines in grid mode. Boolean (True/False). |
| facet_comparison_stroke_color | Line color |
| facet_comparison_stroke_width | Line width |
| facet_comparison_stroke_opacity | Line opacity |
| facet_comparison_fill | Area fill color |
| facet_comparison_fill_opacity | Area fill opacity |
| radial_axis_show | Allowed values: true (Visible), false (Hidden) |
| radial_axis_x_line_color | Line color |
| radial_axis_x_line_width | Width. |
| radial_axis_x_tick_label_color | Color. |
| radial_axis_x_tick_label_size | Size. |
| radial_axis_x_tick_label_outline | Outline. Max: 1 |
| radial_axis_x_tick_label_weight | Allowed values:"bold","normal" |
| radial_axis_y_minimum | minimum value. |
| radial_axis_y_maximum | maximum value. |
| radial_axis_y_tick_number | Number. |
| radial_axis_y_line_color | Color. |
| radial_axis_y_line_width | Width. |
| radial_axis_y_line_dash | Dash. |
| radial_axis_y_line_dash_gap | Gap. |
| radial_axis_y_tick_label_color | Color. |
| radial_axis_y_tick_label_size | Size. |
| radial_axis_y_tick_label_outline | Outline. Max: 1 |
| radial_axis_y_tick_label_space | Space. |
| radial_axis_y_tick_label_weight | Allowed values:"bold","normal" |
| radial_axis_margin_top | Top. |
| radial_axis_margin_right | Right. |
| radial_axis_margin_bottom | Bottom. |
| radial_axis_margin_left | Left. |
| radial_axis_group_labels_custom_value | Outer label custom value (e.g. c('my label 1', 'my label 2')). |
| radial_axis_group_labels_custom_angle | Outer label custom value (e.g. c(45, 90)). |
| radial_axis_group_labels_color | Color. |
| radial_axis_group_labels_size | Size. |
| radial_axis_group_labels_letter_spacing | Letter spacing. |
| radial_axis_group_labels_space_above | Space above. |
| radial_axis_group_labels_space_below | Space below. |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

