---
title: "Set pictogram details"
---

*R/details.R*

## set_pictogram_details

## Description
 Set pictogram details 


## Usage
```r
 
set_pictogram_details( 
  ., 
  bar_orientation = NULL, 
  flip_bars = NULL, 
  bar_padding = NULL, 
  icons = NULL, 
  icon_padding = NULL, 
  auto_icon_value = NULL, 
  icon_value = NULL, 
  icon_color = NULL, 
  icon_style = NULL, 
  icon_stroke_thickness = NULL, 
  use_filler_icons = NULL, 
  filler_icon_color = NULL, 
  max_bar_value = NULL, 
  fill_final_row = NULL, 
  filler_icons = NULL, 
  show_bar_labels = NULL, 
  bar_label_size = NULL, 
  bar_label_color = NULL, 
  bar_label_weight = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| bar_orientation | Bar orientation. Defines the orientation of the bars (vertical or horizontal). Allowed values: "vertical", "horizontal". |
| flip_bars | Boolean (True/False). Flip bars. Flip the bars so they point in the opposite direction |
| bar_padding | Bar padding (%). Padding surrounding bars (as a percentage of bar width). Max: 100 |
| icons | Icons. Use your own icons using icon bindings or choose a built in icon. Allowed values: "auto",,"user", "female", "male", "baby", "child", "wheelchair", "angry", "frown", "meh", "smile", "smile-beam", "thumbs-up", "thumbs-down", "hands-helping", "hand-rock", "hand-peace", "dollar-sign", "euro-sign", "money-bill", "money-bill-wave", "pound-sign", "coins", "shopping-bag", "shopping-cart", "circle", "square", "star", "heart", "comment", "cat", "dog", "dove", "bus", "car", "biking", "running", "plane", "suitcase", "pizza-slice", "ice-cream", "coffee", "wine-glass-alt", "building", "home", "store", "industry", "database", "laptop", "microchip", "phone", "mobile-alt", "tv", "clock", "atom", "award", "music", "leaf", "lightbulb", "sun", "wrench", "airbnb", "amazon", "android", "apple", "bitcoin", "facebook", "google", "linux", "microsoft", "twitter", "windows", "youtube". |
| icon_padding | Icon padding (%). Padding surrounding icons (as a percentage of the icon size). Max: 100 |
| auto_icon_value | Boolean (True/False). Auto icon value. Automatically compute a sensible value for each icon |
| icon_value | Icon value. The value that each icon represents |
| icon_color | Icon color. The color of the icons |
| icon_style | Icon style. The style (solid or outline) of the icons. Allowed values: "solid", "outline" |
| icon_stroke_thickness | Icon outline thickness (%). The outline thickness (as a percentage of the icon size). Min: 1. Max: 100 |
| use_filler_icons | Use filler icons. Boolean (True/False). Fill empty space with icons |
| filler_icon_color | Filler icon color. Color of filler icons |
| max_bar_value | Maximum bar value. (Optional) Maximum bar value (remaining bar space will be filled with filler icons). A value less than the largest bar value is disregarded. |
| fill_final_row | Fill final row. Boolean (True/False). Fill the final row of icons with filler icons (so that a grid of icons is formed) |
| filler_icons | Filler icon. Icon used to fill remaining space. Allowed values: "auto",,"user", "female", "male", "baby", "child", "wheelchair", "angry", "frown", "meh", "smile", "smile-beam", "thumbs-up", "thumbs-down", "hands-helping", "hand-rock", "hand-peace", "dollar-sign", "euro-sign", "money-bill", "money-bill-wave", "pound-sign", "coins", "shopping-bag", "shopping-cart", "circle", "square", "star", "heart", "comment", "cat", "dog", "dove", "bus", "car", "biking", "running", "plane", "suitcase", "pizza-slice", "ice-cream", "coffee", "wine-glass-alt", "building", "home", "store", "industry", "database", "laptop", "microchip", "phone", "mobile-alt", "tv", "clock", "atom", "award", "music", "leaf", "lightbulb", "sun", "wrench", "airbnb", "amazon", "android", "apple", "bitcoin", "facebook", "google", "linux", "microsoft", "twitter", "windows", "youtube". |
| show_bar_labels | Show bar labels. Boolean (True/False) |
| bar_label_size | Bar label size (relative to the root font size). Max: 10 |
| bar_label_color | Bar label color |
| bar_label_weight | Bar label weight. Allowed values:"bold","normal" |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

