---
title: "Set countdown details"
---

*R/details.R*

## set_countdown_details

## Description
 Set countdown details 


## Usage
```r
 
set_countdown_details( 
  ., 
  date_day = NULL, 
  date_month = NULL, 
  date_year = NULL, 
  date_hour = NULL, 
  date_minute = NULL, 
  date_second = NULL, 
  display_mode = NULL, 
  custom_template = NULL, 
  finished_text = NULL, 
  countdown_text_size = NULL, 
  countdown_text_color = NULL, 
  countdown_text_weight = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| date_day | Day in numeric value. Min: 1; max: 31. |
| date_month | Month in numeric value. Min: 1; max: 12. |
| date_year | Year in numeric value. Min: 2021. |
| date_hour | Hour in numeric value. Min: 0; max: 23. |
| date_minute | Minute in numeric value. Min: 0; max: 59. |
| date_second | Second in numeric value. Min: 0; max: 24 |
| display_mode | Countdown format. Allowed values:"auto","custom". |
| custom_template | Custom format. Can include any text or HTML. Use d   for days, h   for hours, m   for minutes and s   for seconds. |
| finished_text | Display text when finished. |
| countdown_text_size | Size in vw - this makes sure it always scales with the page. |
| countdown_text_color | Color |
| countdown_text_weight | Weight. Allowed values:"normal","bold". |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

