---
title: "Set details on line charts"
---

*R/details.R*

## set_line_details

## Description
 Set details on line charts 


## Usage
```r
 
set_line_details( 
  ., 
  plot_grid_across_columns = NULL, 
  line_width = NULL, 
  line_opacity = NULL, 
  line_curve = NULL, 
  line_dash_items = NULL, 
  line_dash_width = NULL, 
  line_dash_space_width = NULL, 
  line_interpolate = NULL, 
  shade_between_lines_line_1 = NULL, 
  shade_between_lines_line_2 = NULL, 
  shade_between_lines_color = NULL, 
  shade_between_lines_opacity = NULL, 
  point_mode = NULL, 
  point_opacity = NULL, 
  point_radius = NULL, 
  point_radius_last = NULL, 
  point_hollow = NULL, 
  line_end_labels = NULL, 
  line_end_labels_max_width = NULL, 
  line_end_labels_text_padding_horizontal = NULL, 
  line_end_labels_position = NULL, 
  line_end_labels_text_padding_vertical = NULL, 
  line_end_labels_hide_overlaps = NULL, 
  line_end_labels_text_color = NULL, 
  line_end_labels_text_size = NULL, 
  line_end_labels_text_bg_color = NULL, 
  line_end_labels_text_bg_size = NULL, 
  line_end_labels_text_line_height = NULL, 
  line_end_labels_text_max_lines = NULL, 
  line_end_labels_text_weight = NULL, 
  line_end_labels_connector_lines = NULL, 
  line_end_labels_connector_lines_style = NULL, 
  line_end_labels_connector_lines_color = NULL, 
  line_end_labels_connector_lines_width = NULL, 
  line_end_labels_connector_lines_range = NULL, 
  line_end_labels_connector_lines_padding = NULL, 
  show_labels_on_datapoints = NULL, 
  labels_hide_overlaps = NULL, 
  labels_dot_center = NULL, 
  labels_fixed_color = NULL, 
  labels_font_weight = NULL, 
  labels_font_size_mode = NULL, 
  labels_font_size = NULL, 
  labels_bg_mode = NULL, 
  labels_bg_size = NULL, 
  labels_content = NULL, 
  dual_axis = NULL, 
  secondary_axis = NULL, 
  sort_mode = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| plot_grid_across_columns | Boolean (True/False). Plot small multiples across multiple columns. If you want to split by the value within one column, define the grid call in `bind_data()`. |
| line_width | Width. In rems, a multiple of the page's base font size |
| line_opacity | Opacity. Max: 1 |
| line_curve | Line curve. Allowed values: curveLinear (Straight), curveMonotoneX (Curve (X)), curveNatural (Curve (Natural)), curveStep (Step), curveStepBefore (Step Before), curveStepAfter (Step After) |
| line_dash_items | Dashed lines. Specify the column(s) you would like to display |
| line_dash_width | Dash width. |
| line_dash_space_width | Space between dash width. |
| line_interpolate | Missing data points. Allowed values: True (contine line), False (gaps in line). |
| shade_between_lines_line_1 | Start of line shade |
| shade_between_lines_line_2 | End of line shade |
| shade_between_lines_color | Line shade color |
| shade_between_lines_opacity | Line shade opacity |
| point_mode | "Auto” will automatically show dots on lines if fewer than 250 data points; avoid showing dots for large datasets since it can lead to poor performance issues and poor-looking charts. Allowed values: auto, on, off. |
| point_opacity | Point opacity. Max: 1 |
| point_radius | Point radius  In rems, a multiple of the page's base font size. Max: 3 |
| point_radius_last | Final dot scale (%). Making the last point on a line larger can help emphasise the final value. |
| point_hollow | Hollow points. Boolean (True/False) |
| line_end_labels | Show end labels on lines |
| line_end_labels_max_width | maximum label width. The maximum allowed label width |
| line_end_labels_text_padding_horizontal | Distance. The horizontal space between the data point and the label |
| line_end_labels_position | Spread out overlaps. Whether to spread out labels to minimise overlapping. Allowed values: spread-y (On), none (Off) |
| line_end_labels_text_padding_vertical | Vertical padding. The vertical space left between labels when spreading them out to avoid overlaps |
| line_end_labels_hide_overlaps | Hide overlaps. Whether to hide any labels that are overlapping in their final position |
| line_end_labels_text_color | Color. If cleared, uses the main text color from the Layout settings panel |
| line_end_labels_text_size | Size. Max: 100 |
| line_end_labels_text_bg_color | Outline. If cleared, uses the main background color from the Layout settings panel |
| line_end_labels_text_bg_size | Outline width. As a % of the font size Max: 100 |
| line_end_labels_text_line_height | Line height |
| line_end_labels_text_max_lines | maximum lines per label |
| line_end_labels_text_weight | Text weight. Allowed values:"normal","bold" |
| line_end_labels_connector_lines | Connector lines. Allowed values: auto (Auto), on (On), off (Off) |
| line_end_labels_connector_lines_style | Line style. Allowed values: straight (Straight), step (Step) |
| line_end_labels_connector_lines_color | Color. If cleared, uses the main text color from the Layout settings panel |
| line_end_labels_connector_lines_width | Width. In rems (a multiple of base font size). Max: 0.5 |
| line_end_labels_connector_lines_range | Length. The width of the space given over to lines; in rems, a multiple of base font size |
| line_end_labels_connector_lines_padding | Padding. The padding to the left and right of the line; in rems, a multiple of base font size |
| show_labels_on_datapoints | Show labels on data points. Boolean (True/False) |
| labels_hide_overlaps | Hide overlapping labels.  Boolean (True/False) |
| labels_dot_center | Position labels on center of dot.  Boolean (True/False) |
| labels_fixed_color | Color |
| labels_font_weight | Font weight. Allowed values:"bold","normal". |
| labels_font_size_mode | Size. Allowed values:"auto","fixed". |
| labels_font_size | Size. |
| labels_bg_mode | Outline. A text outline/background can make the text more readable by increasing contrast. Allowed values: on (On), off (Off) |
| labels_bg_size | Size. Size of the background, as % of text size. Max: 100 |
| labels_content | Label content. Allowed values: auto (Auto), value (Value), label (Label), both (Both) |
| dual_axis | Axis type. Allowed values: false (Single), true (Dual) |
| secondary_axis | Number of combo lines. Sets how many of your specified value columns are treated as lines (or lines on the right axis in line-line mode). Counts from the start, so if you want, say, column B as a line and A as a column, set the order in the column settings to"B,A". |
| sort_mode | Sort mode. Allowed values: data (Data sheet), value (Value), label (Label) |






## See Also
 Other Flourish line, bar, pie chart and scatterplots:  `bind_data()`, `bind_racing_bar_chart_data()`, `bind_racing_line_chart_data()`, `set_area_details()`, `set_bar_column_details()`, `set_boxplot_details()`, `set_racing_bar_chart_details()`, `set_racing_line_chart_details()`, `set_scatterplot_details()`, `set_segment_details()`, `set_violin_details()` 

