---
title: "Bind network data"
---

*R/bindings.R*

## bind_network_data

## Description
 Bind network data 


## Usage
```r
 
bind_network_data( 
  ., 
  links_data = NULL, 
  links_source_name = NULL, 
  links_target_name = NULL, 
  links_value = NULL, 
  nodes_data = NULL, 
  nodes_id = NULL, 
  nodes_group = NULL, 
  nodes_size = NULL, 
  nodes_image = NULL, 
  nodes_add_to_popup_panel = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| links_data | A data frame |
| links_source_name | source |
| links_target_name | target |
| links_value | A numerical value used to set the thickness of the links |
| nodes_data | An optional data frame with additional information about nodes |
| nodes_id | A unique identifier for each point in the network. If not specified, point information will be extracted from the links sheet. |
| nodes_group | A group to which the point belongs. If set, can be used to color the points. Ignored if ID not set. |
| nodes_size | Size of the node. |
| nodes_image | An image to go into the circle |
| nodes_add_to_popup_panel | Specify additional columns to include in custom popup text (popup text must also be specified in settings panel). Ignored if ID not set |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

