---
title: "Bind up data bindings for line chart"
---

*R/bindings.R*

## bind_racing_line_chart_data

## Description
 Bind up data bindings for line chart 


## Usage
```r
 
bind_racing_line_chart_data( 
  ., 
  race_data = NULL, 
  race_name = NULL, 
  race_score = NULL, 
  race_color_category = NULL, 
  race_image = NULL, 
  race_filter = NULL, 
  captions_data = NULL, 
  captions_stage_to_show = NULL, 
  captions_stage_to_hide = NULL, 
  captions_text = NULL, 
  captions_image = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| race_data | Race data frame. |
| race_name | The name of each entrant. (Mandatory.) |
| race_score | Raw scores, which will be automatically converted to ranks. Column names will be used to populate the x-axis of the chart. |
| race_color_category | Select a column to color the lines by. If omitted, colors will be assigned per name. |
| race_image | The URL of the image to use |
| race_filter | Hide/show entrants based on the values in this column. |
| captions_data | An optional data frame for popup captions. |
| captions_stage_to_show | Must match the column headers in the main data sheet |
| captions_stage_to_hide | Must match the column headers in the main data sheet |
| captions_text | Text or HTML to show |
| captions_image | Image to show |






## See Also
 Other Flourish line, bar, pie chart and scatterplots:  `bind_data()`, `bind_racing_bar_chart_data()`, `set_area_details()`, `set_bar_column_details()`, `set_boxplot_details()`, `set_line_details()`, `set_racing_bar_chart_details()`, `set_racing_line_chart_details()`, `set_scatterplot_details()`, `set_segment_details()`, `set_violin_details()` 

