---
title: "Bind gantt chart data"
---

*R/bindings.R*

## bind_gantt_data

## Description
 Bind gantt chart data 


## Usage
```r
 
bind_gantt_data( 
  ., 
  data = NULL, 
  start_date = NULL, 
  end_date = NULL, 
  task = NULL, 
  grouping = NULL, 
  color = NULL, 
  progress = NULL, 
  add_to_popup_panel = NULL, 
  filter = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| data | Gantt data set |
| start_date | start_date |
| end_date | The end date or time of the event. If working with days, the end date should be the first day after the end date. So if your event stretches from 1/1. and ends on the 5/1. your end date should be the 6/1. This way your gantt bar will stretch across the last day of your project or task. |
| task | task |
| grouping | Select a categorical column to combine bars into groups on the Y axis |
| color | Select a categorical column; each unique value in the column will become a color |
| progress | Requires a number column with values between 0 and 1, representing the progress from 0 to 100%. |
| add_to_popup_panel | Add any columns here containing extra content to show in the popups |
| filter | If set, creates a filter menu or time slider |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

