---
title: "Bind up region or marker map data"
---

*R/bindings.R*

## bind_region_marker_map_data

## Description
 Bind up region or marker map data 


## Usage
```r
 
bind_region_marker_map_data( 
  ., 
  regions_data = NULL, 
  regions_geometry = NULL, 
  regions_name = NULL, 
  regions_value = NULL, 
  regions_height = NULL, 
  regions_color_category = NULL, 
  regions_add_to_popup_panel = NULL, 
  inset_regions_data = NULL, 
  inset_regions_geometry = NULL, 
  icons_data = NULL, 
  icons_category = NULL, 
  icons = NULL, 
  icons_size = NULL, 
  icons_color = NULL, 
  icons_opacity = NULL, 
  markers_data = NULL, 
  markers_latitude = NULL, 
  markers_longitude = NULL, 
  markers_image = NULL, 
  markers_name = NULL, 
  markers_description = NULL, 
  markers_photo = NULL, 
  markers_link = NULL, 
  markers_category = NULL, 
  markers_color = NULL, 
  markers_size = NULL, 
  markers_metadata = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| regions_data | An `sf` data frame for map regions. |
| regions_geometry | The geometry column |
| regions_name | Name column |
| regions_value | Value for map. |
| regions_height | Height for Z axis. |
| regions_color_category | Color category for map. |
| regions_add_to_popup_panel | Add information to popups or panels. |
| inset_regions_data | An `sf` dataframe for inset map |
| inset_regions_geometry | Inset map geometry. |
| icons_data | A data frame for icons. |
| icons_category | Values should match the 'markers_category' column in the markets sheet, and should not be repeated. |
| icons | Can be a Font Awesome icon name, e.g. 'circle' or 'chevron-right'; an image URL; or an emoji. Images can be no larger than 1024x1024 pixels. |
| icons_size | Amount to scale the icon by. |
| icons_color | Color of the icon - this can be a hex value like '#fff', or a web-safe value like 'red'. Note that this is only available when using Font Awesome icons, not emoji or uploaded images. |
| icons_opacity | Opacity of the icon between 0 and 1, e.g. 0.5. |
| markers_data | A data frame for markers. |
| markers_latitude | Latitude (Y axis) |
| markers_longitude | Longitude (X axis) |
| markers_image | Can include emojis, Font Awesome icons or uploaded images. Uploaded images can be no larger than 1024x1024 pixels. |
| markers_name | Name of place, shown in popup |
| markers_description | Description of place, shown in popup |
| markers_photo | Photo to be included in popup |
| markers_link | link to be included in popup |
| markers_category | Category of place. Values should match the 'icons_category' column. |
| markers_color | Color of the icon - this can be a hex value like '#fff', or a web-safe value like 'red'. Note that this is only available for Font Awesome icons. |
| markers_size | size |
| markers_metadata | Extra metadata to show in the popup. Add as many columns as you like. |






## See Also
 Other Flourish map:  `bind_arc_map_data()`, `bind_choropleth_map_data()`, `bind_connections_globe_data()`, `bind_time_map_data()`, `set_arc_map_details()`, `set_choropleth_map_details()`, `set_connections_globe_details()`, `set_marker_map_details()`, `set_region_map_details()`, `set_time_map_details()` 

