---
title: "Bind sunburst data"
---

*R/bindings.R*

## bind_sunburst_data

## Description
 Bind sunburst data 


## Usage
```r
 
bind_sunburst_data( 
  ., 
  data = NULL, 
  nest_by = NULL, 
  size = NULL, 
  filter = NULL, 
  add_to_panel_popup = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| data | A data frame |
| nest_by | Choose categorical columns to nest by (e.g. C,B,A). The data is nested in the same order as the chosen columns. For example if the chosen columns are 'C,B' the data is first grouped by Lead Studio and then by Genre. |
| size | (Optional) Choose numeric columns to size by (e.g. Worldwide Gross). If more than 1 is chosen, a dropdown will appear in the visualisation which lets the user choose. Rows with negative values are excluded. |
| filter | (Optional) Choose a categorical column to filter by. A dropdown will appear in the visualization. |
| add_to_panel_popup | Makes additional columns (text, emoji, image URLs, etc) available in custom popups |






## See Also
 Other Flourish heatmap or hierarchy charts:  `bind_circle_packing_data()`, `bind_heatmap_data()`, `bind_hierarchical_bar_data()`, `bind_hierarchy_data`, `bind_radial_tree_data()`, `bind_treemap_data()`, `set_circle_packing_details()`, `set_heatmap_details()`, `set_hierarchical_bar_details()`, `set_radial_tree_details()`, `set_sunburst_details()`, `set_treemap_details()` 

