---
title: "Set Flourish chart background"
---

*R/chart.R*

## chart_background

## Description
 Set Flourish chart background 


## Usage
```r
 
chart_background( 
  ., 
  background_color = NULL, 
  background_image_source = NULL, 
  background_image_size = NULL, 
  background_image_position = NULL, 
  max_width = NULL, 
  max_width_target = NULL, 
  max_width_align = NULL, 
  layout_order = NULL, 
  space_between_sections = NULL, 
  space_between_sections_custom = NULL, 
  margin = NULL, 
  margin_top = NULL, 
  margin_right = NULL, 
  margin_bottom = NULL, 
  margin_left = NULL, 
  border_width = NULL, 
  border_style = NULL, 
  border_color = NULL, 
  border_top_width = NULL, 
  border_top_style = NULL, 
  border_top_color = NULL, 
  border_left_width = NULL, 
  border_left_style = NULL, 
  border_left_color = NULL, 
  border_bottom_width = NULL, 
  border_bottom_style = NULL, 
  border_bottom_color = NULL, 
  border_right_width = NULL, 
  border_right_style = NULL, 
  border_right_color = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| background_color | Background color. |
| background_image_source | Image URL |
| background_image_size | Image size. Allowed strings: c("cover", "contain", "auto", "100% 100%"), |
| background_image_position | Image position. Allowed strings: c("top left", "top center", "top right",  "center left", "center right", "bottom left", "bottom center", "bottom right"), |
| max_width | Maximum width of container. Defaults to HTML element width if left blank. Min value: 50 |
| max_width_target | Maximum width. Apply a maximum width to just the main graphic or everything (main graphic plus header, footer, etc). Allowed strings: c("none", "wrapper", "primary", NULL), |
| max_width_align | Alignment of container. Allowed strings: c("left", "center", "right") |
| layout_order | Order of chart elements. Allowed strings: c("stack-default", "stack-2", "stack-3", "stack-4") |
| space_between_sections | Space between axes elements. Allowed numeric values: c(0.5, 1, 1.5), |
| space_between_sections_custom | Set custom space between axes elements. Max value: 100 |
| margin | Margin value |
| margin_top | Margin top numeric value |
| margin_right | Margin right numeric value |
| margin_bottom | Margin bottom numeric value |
| margin_left | Margin left numeric value |
| border_width | Border width numeric value |
| border_style | Border style. Allowed strings = c("solid", "dashed", "dotted") |
| border_color | Border color (hex code string) |
| border_top_width | Border top width numeric value |
| border_top_style | Border top style. Allowed strings = c("solid", "dashed", "dotted") |
| border_top_color | Border top color (hex code string) |
| border_left_width | Border left width numeric value |
| border_left_style | Border left style. Allowed strings = c("solid", "dashed", "dotted") |
| border_left_color | Border left color (hex code string) |
| border_bottom_width | Border bottom width numeric value |
| border_bottom_style | Border bottom style. Allowed strings = c("solid", "dashed", "dotted") |
| border_bottom_color | Border bottom color (hex code string) |
| border_right_width | Border right width numeric value |
| border_right_style | Border right style. Allowed strings = c("solid", "dashed", "dotted") |
| border_right_color | Border right color (hex code string) |







