---
title: "Set up Flourish annotations"
---

*R/chart.R*

## chart_annotations

## Description
 Set up Flourish annotations 


## Usage
```r
 
chart_annotations( 
  ., 
  x_label = NULL, 
  x_label_color = NULL, 
  x_label_vertical = NULL, 
  x_label_y_position = NULL, 
  x_label_x_position = NULL, 
  x_label_max_width = NULL, 
  x_line_position = NULL, 
  x_line_x_position = NULL, 
  x_line_y_position = NULL, 
  x_line_color = NULL, 
  x_line_width = NULL, 
  x_line_dash = NULL, 
  x_add_to_grid = NULL, 
  x_area_min_position = NULL, 
  x_area_max_position = NULL, 
  x_area_color = NULL, 
  x_area_opacity = NULL, 
  x_area_texture = NULL, 
  x_font_size = NULL, 
  x_font_weight = NULL, 
  x_shadow_color = NULL, 
  y_label = NULL, 
  y_label_color = NULL, 
  y_label_vertical = NULL, 
  y_label_y_position = NULL, 
  y_label_x_position = NULL, 
  y_label_max_width = NULL, 
  y_line_position = NULL, 
  y_line_color = NULL, 
  y_line_width = NULL, 
  y_line_dash = NULL, 
  y_add_to_grid = NULL, 
  y_area_min_position = NULL, 
  y_area_max_position = NULL, 
  y_area_color = NULL, 
  y_area_opacity = NULL, 
  y_area_texture = NULL, 
  y_font_size = NULL, 
  y_font_weight = NULL, 
  y_shadow_color = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| x_label | Label (string variable); character vector. |
| x_label_color | Label color (string variable); character vector. |
| x_label_vertical | Label position. Boolean (True/False) |
| x_label_y_position | Y position. Vertically position the label at the top, bottom or in the middle of the line. This setting will be ignored if there is not enough space for the selected position. Allowed values: "bottom", "middle", "top" |
| x_label_x_position | X position. Horizontally position the label on the left, the right or in the middle of the line. This setting will be ignored if there is not enough space for the selected position. Allowed values: "left", "middle", "right" |
| x_label_max_width | Max width. Min: 1 |
| x_line_position | X-intercept for line; character vector. |
| x_line_x_position | Offset X-intercept line. |
| x_line_y_position | Offset Y-intercept line. |
| x_line_color | Line color; character vector. |
| x_line_width | Line width. |
| x_line_dash | Dash type. |
| x_add_to_grid | Name of grid if applying annotation to one part of grid |
| x_area_min_position | Start of area range along X axis |
| x_area_max_position | End of area area range along X axis |
| x_area_color | Area color |
| x_area_opacity | Area opacity |
| x_area_texture | Area texture. Allowed values: "none", "diagonal", "grid", "dots |
| x_font_size | Label font size |
| x_font_weight | Label font weight - "normal", "bold" |
| x_shadow_color | Shadow color |
| y_label | Label (string variable); character vector. |
| y_label_color | Label color (string variable); character vector. |
| y_label_vertical | Label position. Boolean (True/False) |
| y_label_y_position | Y position. Vertically position the label above, below or in the middle of the line. This setting will be ignored if there is not enough space for the selected position Allowed values: "above", "middle", "below" |
| y_label_x_position | X position. Horizontally position label on the left, the middle or the right end of the line. This setting will be ignored if there is not enough space for the selected position. Allowed values: "left", "middle", "right" |
| y_label_max_width | Max width. Min: 1 |
| y_line_position | A vector of line position along Y axis. |
| y_line_color | A vector of line colors |
| y_line_width | Line width |
| y_line_dash | Line dash |
| y_add_to_grid | A vector of name of grid if adding annotation to a specific grid |
| y_area_min_position | Start of area range along Y axis |
| y_area_max_position | End of area range along Y axis |
| y_area_color | Area color |
| y_area_opacity | Area opacity |
| y_area_texture | Area texture. Allowed values: "none", "diagonal", "grid", "dots" |
| y_font_size | Label font size |
| y_font_weight | Label font weight - "normal", "bold" |
| y_shadow_color | Shadow color. |







