---
title: "Set chord diagram details"
---

*R/details.R*

## set_chord_diagram_details

## Description
 Set chord diagram details 


## Usage
```r
 
set_chord_diagram_details( 
  ., 
  opacity_default = NULL, 
  opacity_focused = NULL, 
  opacity_defocused = NULL, 
  selected_chords = NULL, 
  use_mouseover_label = NULL, 
  show_selected_label = NULL, 
  chord_labels_reponsive = NULL, 
  chord_label_font_size = NULL, 
  chord_label_font_size_minimum = NULL, 
  chord_label_font_size_maximum = NULL, 
  show_chord_stroke = NULL, 
  chord_stroke_color = NULL, 
  chord_stroke_opacity = NULL, 
  arc_thickness = NULL, 
  arc_spacing = NULL, 
  pad_angle = NULL, 
  label_alignment = NULL, 
  label_responsive = NULL, 
  label_font_size = NULL, 
  label_font_size_minimum = NULL, 
  label_font_size_maximum = NULL, 
  label_color = NULL, 
  use_label_color_arc = NULL, 
  gradient_type = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| opacity_default | Default opacity. Opacity for the default view. Max: 1 |
| opacity_focused | Focused opacity. Opacity for the selected and/or hovered chords. Max: 1 |
| opacity_defocused | Defocused opacity. Opacity for the background chords when one is in focus. Max: 1 |
| selected_chords | Highlight chords. You can highlight all of an arc's chords by typing the name of the arc. Alternatively, you can highlight individual chords by typing the name of the two arcs that it connects using the format"Arc 1 >> Arc 2". If you wanted to highlight all chords from"Arc 3" and any chords between"Arc 1" and"Arc 2" you would write: c("Arc 3", "Arc 1 >> Arc 2"). |
| use_mouseover_label | Show chord values on hover. Boolean (True/False) |
| show_selected_label | Keep chord values on click. Boolean (True/False) |
| chord_labels_reponsive | Label text size. Boolean (True/False). Auto changes the label size based on the window size, subject to the specified minimum and max. |
| chord_label_font_size | Text size. Max: 4 |
| chord_label_font_size_minimum | minimum size. Max: 4 |
| chord_label_font_size_maximum | maximum size. Max: 4 |
| show_chord_stroke | Boolean (True/False) |
| chord_stroke_color | Stroke color. |
| chord_stroke_opacity | Stroke opacity. Max: 1 |
| arc_thickness | Thickness. As a percentage of the radius. Max: 80 |
| arc_spacing | Space below. As a percentage of the radius. Max: 40 |
| pad_angle | Space between. In degrees. Max: 180 |
| label_alignment | Alignment. Allowed values: along_arcs, 90_rotated (90° rotated) |
| label_responsive | Label text size. Boolean (True/False). Auto changes the label size based on the window size, subject to the specified minimum and max |
| label_font_size | Text size. Max: 4 |
| label_font_size_minimum | minimum size. Max: 4 |
| label_font_size_maximum | maximum size. Max: 4 |
| label_color | Label color. |
| use_label_color_arc | Boolean (True/False). Make the arc label color the same as the arc color. |
| gradient_type | Chord color mode. Allowed values: linear_gradient, largest_end, smallest_end |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

