---
title: "Set treemap details"
---

*R/details.R*

## set_treemap_details

## Description
 Set treemap details 


## Usage
```r
 
set_treemap_details( 
  ., 
  treemap_aspect_ratio_normal = NULL, 
  treemap_aspect_ratio_narrow = NULL, 
  responsive_narrow_breakpoint = NULL, 
  treemap_type = NULL, 
  treemap_ratio = NULL, 
  cell_padding = NULL, 
  number_of_visible_levels = NULL, 
  sort_by = NULL, 
  aggregation_type = NULL, 
  auto_set_height = NULL, 
  label_size = NULL, 
  min_label_size = NULL, 
  max_label_size = NULL, 
  label_padding = NULL, 
  multi_line_labels = NULL, 
  label_case = NULL, 
  label_weight = NULL, 
  value_labels_bold = NULL, 
  bar_value_label_space = NULL, 
  stroke_color = NULL, 
  zoom_out_button_color = NULL, 
  zoom_out_arrow_color = NULL, 
  label_color = NULL, 
  axis_label_color = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| treemap_aspect_ratio_normal | Aspect (desktop). Height of treemap, as % of width |
| treemap_aspect_ratio_narrow | Aspect (mobile). Height of treemap, as % of width |
| responsive_narrow_breakpoint | Breakpoint. The width at which mobile mode ends and desktop begins |
| treemap_type | Layout mode. Allowed values: treemapBinary (Default), treemapResquarify (Aspect ratio), treemapSlice (Horizontal), treemapDice (Vertical), treemapSliceDice (Horizontal then Vertical), |
| treemap_ratio | Target. The target ratio between width and height, where 1 is sqaure and a large number is a tall or wide rectangle. Min: 1 |
| cell_padding | Padding. Add padding between hierarchy levels. Allowed values: low (Thin), medium (Medium), high (Thick) |
| number_of_visible_levels | Visible levels. How many hierarchy levels are visible at once? Min: 1 |
| sort_by | Sort by. Sort cells by value or by name. (In Circles layout, the circles are placed in the specified order following an approximately spiral path.) Allowed values: "data", "value", "name" |
| aggregation_type | Size cells by "sum" or "count". |
| auto_set_height | Auto set height. Automatically determine container height. For example circle packing, sunburst and radial tree will fill width and treemap will use the specified aspect ratio. |
| label_size | Label size. Label size (relative to root font size). Min: 0.1 |
| min_label_size | Minimum label size. Minimum label size (relative to root font size). Min: 0.1 |
| max_label_size | Maximum label size. Maximum label size (relative to root font size) |
| label_padding | Label padding. Padding (relative to root font size) between label and border. Max: 2 |
| multi_line_labels | Boolean (True/False). Multi line labels. Display long labels across multiple lines where possible. Currently supported in treemap and circle packing. |
| label_case | Label case. Determines whether labels are lower or upper case. Items at the top level of the hierarchy can have a different case to the remaining items. Allowed values: allUpperCase (All labels upper case), allLowerCase (All labels lower case), topUpperCase (Top labels upper case), bottomUpperCase (Bottom labels upper case) |
| label_weight | Label weight. Determines the font weight (normal or bold) of labels. Items at the top level of the hierarchy can have a different weight to the remaining items. Allowed values: allNormal (All labels normal), allBold (All labels bold), topBold (Top labels bold), bottomBold (Bottom labels bold) |
| value_labels_bold | Bold value labels. Boolean (True/False). |
| bar_value_label_space | Space for value labels. Space available for value labels (relative to root font size) |
| stroke_color | Stroke color. |
| zoom_out_button_color | Button colour. |
| zoom_out_arrow_color | Arrow colour. |
| label_color | Label color. |
| axis_label_color | Axis color. |






## See Also
 Other Flourish heatmap or hierarchy charts:  `bind_circle_packing_data()`, `bind_heatmap_data()`, `bind_hierarchical_bar_data()`, `bind_hierarchy_data`, `bind_radial_tree_data()`, `bind_sunburst_data()`, `bind_treemap_data()`, `set_circle_packing_details()`, `set_heatmap_details()`, `set_hierarchical_bar_details()`, `set_radial_tree_details()`, `set_sunburst_details()` 

