---
title: "Set details on donut/pie charts"
---

*R/details.R*

## set_segment_details

## Description
 Set details on donut/pie charts 


## Usage
```r
 
set_segment_details( 
  ., 
  donut_inner_radius = NULL, 
  donut_corner_radius = NULL, 
  donut_pad_angle = NULL, 
  donut_auto_scale = NULL, 
  labels_hide_overlaps = NULL, 
  labels_fixed_color = NULL, 
  labels_font_weight = NULL, 
  labels_font_size_mode = NULL, 
  labels_font_size = NULL, 
  labels_bg_mode = NULL, 
  labels_bg_size = NULL, 
  labels_content = NULL, 
  sort_mode = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| donut_inner_radius | Doughnut hole (%). Max: 99. |
| donut_corner_radius | Corner curve (pixels). |
| donut_pad_angle | Segment padding (degrees). Max: 10 |
| donut_auto_scale | Scale pies based on data. Scale each pie chart in the grid so that the area of each segment reflect its value |
| labels_hide_overlaps | Hide overlapping labels.  Boolean (True/False) |
| labels_fixed_color | Color |
| labels_font_weight | Font weight. Allowed values:"bold","normal". |
| labels_font_size_mode | Size. Allowed values:"auto","fixed". |
| labels_font_size | Size. |
| labels_bg_mode | Outline. A text outline/background can make the text more readable by increasing contrast. Allowed values: on (On), off (Off) |
| labels_bg_size | Size. Size of the background, as % of text size. Max: 100 |
| labels_content | Label content. Allowed values: auto (Auto), value (Value), label (Label), both (Both) |
| sort_mode | Sort mode. Allowed values: data (Data sheet), value (Value), label (Label) |






## See Also
 Other Flourish line, bar, pie chart and scatterplots:  `bind_data()`, `bind_racing_bar_chart_data()`, `bind_racing_line_chart_data()`, `set_area_details()`, `set_bar_column_details()`, `set_boxplot_details()`, `set_line_details()`, `set_racing_bar_chart_details()`, `set_racing_line_chart_details()`, `set_scatterplot_details()`, `set_violin_details()` 

