---
title: "Set quiz details"
---

*R/details.R*

## set_quiz_details

## Description
 Set quiz details 


## Usage
```r
 
set_quiz_details( 
  ., 
  color_primary = NULL, 
  color_neutral = NULL, 
  color_correct = NULL, 
  block_text_color = NULL, 
  text_border_color = NULL, 
  block_text_size = NULL, 
  block_background = NULL, 
  block_padding = NULL, 
  block_border_width = NULL, 
  block_border_color = NULL, 
  block_border_radius = NULL, 
  block_shadow = NULL, 
  block_shadow_blur = NULL, 
  block_shadow_opacity = NULL, 
  block_button_text_color = NULL, 
  block_button_text_size = NULL, 
  show_all_questions = NULL, 
  slider_handle_color = NULL, 
  slider_handle_radius = NULL, 
  slider_handle_stroke = NULL, 
  slider_channel_color = NULL, 
  slider_channel_height = NULL, 
  slider_comparison_opacity = NULL, 
  slider_range_type = NULL, 
  slider_range_minimum = NULL, 
  slider_range_maximum = NULL, 
  slider_range_step = NULL, 
  slider_range_custom = NULL, 
  multiple_choice_background_color = NULL, 
  multiple_choice_border_color = NULL, 
  multiple_choice_border_width = NULL, 
  multiple_choice_border_radius = NULL, 
  show_dropdown = NULL, 
  dropdown_default_label = NULL, 
  dropdown_label_color = NULL, 
  dropdown_label_text = NULL, 
  score_slider_minimum = NULL, 
  score_slider_maximum = NULL, 
  score_slider_offset = NULL, 
  score_multiple_choice_correct = NULL, 
  score_multiple_choice_incorrect = NULL, 
  end_result_default_text = NULL, 
  text_your_answer = NULL, 
  text_submit = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| color_primary | Color - Primary. |
| color_neutral | Color - Neutral. |
| color_correct | Color - Correct. |
| block_text_color | Color. |
| text_border_color | Border color. |
| block_text_size | Specify a custom responsive font size. Best results will be with values between 1.2 and 3 |
| block_background | Background color. |
| block_padding | Padding. |
| block_border_width | Width. |
| block_border_color | Color. |
| block_border_radius | Radius. |
| block_shadow | Boolean (True/False) |
| block_shadow_blur | Number |
| block_shadow_opacity | Opacity. Max: 1 |
| block_button_text_color | Text color. |
| block_button_text_size | Specify a custom responsive font size. Best results will be with values between 1.2 and 3 |
| show_all_questions | Boolean (True/False). Show unanswered questions. |
| slider_handle_color | Color. |
| slider_handle_radius | Radius. |
| slider_handle_stroke | Border. |
| slider_channel_color | Color. |
| slider_channel_height | Height. |
| slider_comparison_opacity | Comparison opacity. Max: 1 |
| slider_range_type | Slider range. When in "Auto" mode, the range will go from 0 to nearest power of 10. In "fixed" mode, you can set a fixed range for every question. For "custom" you can set a range for each individual question. Allowed values: "auto", "fixed", "custom" |
| slider_range_minimum | Min. |
| slider_range_maximum | Max. |
| slider_range_step | Step. |
| slider_range_custom | Custom. Set a custom range for each question. Write a new range on each line with the following format: question text,range minimum,range maximum,range step. For example: How many people live in London?, 1000000, 20000000, 1000. |
| multiple_choice_background_color | Background color |
| multiple_choice_border_color | Border color |
| multiple_choice_border_width | Border width |
| multiple_choice_border_radius | Border radius |
| show_dropdown | Dropdown enabled. Boolean (True/False). |
| dropdown_default_label | Default comparison. Type in a that's selected as a default when you load the visualisation. |
| dropdown_label_color | Text color |
| dropdown_label_text | Dropdown label |
| score_slider_minimum | minimum score. This is the minimum score the user will get on a slider question. This is the score you'll get when you're more than 50% off from the answer. |
| score_slider_maximum | maximum score. This is the maximum score the user can get on a slider question. This is the score you'll get when you get the exact answer. |
| score_slider_offset | Free zone. Defined as percentage. This is an area around the correct answer that's still treated as correct. For example. if a slider question goes from 0 to 2000, with the correct answer being 1200 and this setting is set to 2.5, then all submitted answers 5% around 1200 will be treated as correct, in this case anything between 1150 and 1250. Max: 50 |
| score_multiple_choice_correct | Score when correct. |
| score_multiple_choice_incorrect | Score when incorrect |
| end_result_default_text | Default end result text. This is the text that shows up after you've finished the quiz. You can add custom end result text for specific score ranges in the Data tab, inside the "End result" sheet. |
| text_your_answer | Slider your answer. |
| text_submit | Submit button. |






## See Also
 Other Flourish quizzes, surveys, and tables:  `bind_quiz_data()`, `bind_survey_data()`, `bind_table_data()`, `set_survey_details()`, `set_table_details()` 

