---
title: "Set sports race details"
---

*R/details.R*

## set_sports_race_details

## Description
 Set sports race details 


## Usage
```r
 
set_sports_race_details( 
  ., 
  preset_svg = NULL, 
  custom_svg = NULL, 
  track_path_id = NULL, 
  track_lane_width = NULL, 
  track_back_and_forth = NULL, 
  participant_icon_mode = NULL, 
  participant_size = NULL, 
  participant_stroke_width = NULL, 
  participant_stroke_opacity = NULL, 
  participant_fill_opacity = NULL, 
  preset_participant_image = NULL, 
  custom_participant_start_image = NULL, 
  custom_participant_race_image = NULL, 
  custom_participant_finish_image = NULL, 
  image_initial_rotation = NULL, 
  image_initial_flip_x = NULL, 
  image_initial_flip_y = NULL, 
  image_transform_mode = NULL, 
  participant_icon_recolor = NULL, 
  camera_mode = NULL, 
  zoom = NULL, 
  checkpoint_mode = NULL, 
  checkpoints = NULL, 
  times_cumulative = NULL, 
  participant_label_mode = NULL, 
  participant_label_custom = NULL, 
  participant_label_position = NULL, 
  participant_label_color = NULL, 
  participant_label_size = NULL, 
  participant_label_stroke = NULL, 
  participant_label_stroke_size = NULL, 
  participant_label_weight = NULL, 
  participant_highlight_color = NULL, 
  participant_highlight_width = NULL, 
  label_position_time = NULL, 
  label_position_type = NULL, 
  label_medal_time = NULL, 
  label_medal_type = NULL, 
  label_medal_replace_position = NULL, 
  label_finishing_time_enabled = NULL, 
  label_finishing_time_time = NULL, 
  participant_stacking = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| preset_svg | Allowed values: athletics, swimming, cycling |
| custom_svg | Custom SVG text |
| track_path_id | Path ID. The ID of the element in the SVG which defines the centre of the track |
| track_lane_width | Lane width. The distance between each participants |
| track_back_and_forth | Boolean. Whether the track goes back and forth, like a swimming pool, or back to the start, like a race track |
| participant_icon_mode | Icon type. Allowed values: circle, image |
| participant_size | Size. |
| participant_stroke_width | Line width. |
| participant_stroke_opacity | Stroke opacity. Max: 1 |
| participant_fill_opacity | Fill opacity. Max: 1 |
| preset_participant_image | Default images. The images used if no image is included for the participant via the data sheet. Allowed values: runner, swimmer, cyclist |
| custom_participant_start_image | Custom start image URL. The image shown at the start of the race |
| custom_participant_race_image | Custom racing image URL. The image shown while the participant is racing |
| custom_participant_finish_image | Custom finish image URL. The image shown when the participant has finished the race |
| image_initial_rotation | Rotate images. Allowed values: 0, 90, 180, 270 |
| image_initial_flip_x | Boolean. Flip horizontally. |
| image_initial_flip_y | Boolean Flip vertically. |
| image_transform_mode | Direction change. Change the direction of the image based on which way the participant is travelling. "Rotate" rotates the image to face the direction of travel. "Flip horizontally" flips the image horizontally depending on whether the participant is travelling towards the left or right. "Flip vertically" flips the image vertically depending on whether the participant is travelling towards the top or bottom."Flip horizontally and vertically" combines the horizontal and vertical flip settings."Static" doesnt change the direction of the image. Allowed values: rotate (Rotate), flip_x (Flip horizontally), flip_y (Flip vertically), flip_both (Flip horizontally and vertically), static (Static) |
| participant_icon_recolor | Boolean. Recolor icons. Apply colors to differentiate the participants. Works best with greyscale images. In Internet Explorer, the images will be displayed without recoloring. |
| camera_mode | Camera mode. Allowed values: track (Entire track), leader (Follow leader) |
| zoom | Zoom level number. How much to zoom in when playing. Min: 1 |
| checkpoint_mode | Checkpoint mode. Allowed values: laps (Laps), splits (Equal splits), custom (Custom) |
| checkpoints | Checkpoints. Enter the number of laps completed at each recorded checkpoint/column in the data. E.g. "0.5, 1, 1.5, 2" would mean that the times were taken every half a lap. Enter one checkpoint per line. |
| times_cumulative | Boolean. Times are cumulative. Switch on if the time columns represent the cumulative time taken at each checkpoint (e.g. 12, 25, 36). Switch off if the times represent how long individual checkpoints took to complete (e.g. 12, 13, 11). |
| participant_label_mode | Label mode. Determines which labels are drawn. Auto draws as many labels as possible whilst avoiding overlaps. Allowed values: auto (Auto), leader (Leader), all (All) |
| participant_label_custom | Participants to label. Enter the names of the participants to label. These must exactly match the names in your data. Enter one name per line. |
| participant_label_position | Label position. Allowed values: auto (Auto), left (Left), right (Right) |
| participant_label_color | Color. |
| participant_label_size | Size. Min: 0.05 |
| participant_label_stroke | Outline. |
| participant_label_stroke_size | Outline width. As a % of the font size |
| participant_label_weight | Weight. Allowed values: "bold", "normal" |
| participant_highlight_color | Highlight color. |
| participant_highlight_width | Highlight width. |
| label_position_time | Show position. Set to “At finish”, to only show a participants position when theyve completed the race. Set to “During race” to only show a participants position while they are still racing.Allowed values: always (Always), race (During race), finish (At finish) |
| label_position_type | Position to show. Whether to show a participants current position in the race, or their finishing positionAllowed values: current (Current), finish (Finishing) |
| label_medal_time | Show medals. Set to “At finish”, to only show a participant's medal when they've completed the race. Set to “During race” to only show a participant's medal while they are still racing. Allowed values: always (Always), race (During race), finish (At finish) |
| label_medal_type | Medal to show. Whether to show the medal position for a participant at the current point in the race, or the medal they win at the end of the race. Allowed values: current (Current), finish (Finishing) |
| label_medal_replace_position | Boolean. Replace position. Turn on to replace a participant's position label with their medal if they are in a medal position |
| label_finishing_time_enabled | Boolean |
| label_finishing_time_time | Show finishing time. Allowed values: always (Always), finish (At finish) |
| participant_stacking | Determines which participants obscure other participants when they overlap. Allowed values: sheet_order (Data order), rank (Leader first), y_position (Y position) |






## See Also
 Other Sports:  `bind_sports_field_data()`, `bind_sports_race_data()`, `set_sports_field_details()` 

