---
title: "Set heatmap details"
---

*R/details.R*

## set_heatmap_details

## Description
 Set heatmap details 


## Usage
```r
 
set_heatmap_details( 
  ., 
  x_axis_datatype = NULL, 
  x_axis_binning = NULL, 
  x_axis_bin_width = NULL, 
  x_axis_bin_center = NULL, 
  cell_x_margin = NULL, 
  y_axis_datatype = NULL, 
  y_axis_binning = NULL, 
  y_axis_bin_width = NULL, 
  y_axis_bin_center = NULL, 
  cell_y_margin = NULL, 
  height_mode = NULL, 
  cell_height = NULL, 
  cell_aspect = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| x_axis_datatype | Data type. Allowed values:"numeric","categorical". |
| x_axis_binning | Binning mode. Allowed values:"auto","custom". |
| x_axis_bin_width | Bin width. The numeric range of each bin – e.g. a bin width of 10 would give bins of 0–10, 10–20, etc (assuming a bin center of 5). |
| x_axis_bin_center | Bin center. One value you'd like as the center of a bin – e.g. with a bin width of 10, a center of 5 would give 0–10, 10–20, 20–30, etc, while a center of 0 would give -5–5, 5–10, 10–20, etc. |
| cell_x_margin | Cell padding. |
| y_axis_datatype | Data type. Allowed values:"numeric","categorical". |
| y_axis_binning | Binning mode. Allowed values:"auto","custom". |
| y_axis_bin_width | Bin width. The numeric range of each bin – e.g. a bin width of 10 would give bins of 0–10, 10–20, etc (assuming a bin center of 5). |
| y_axis_bin_center | Bin center. One value you'd like as the center of a bin – e.g. with a bin width of 10, a center of 5 would give 0–10, 10–20, 20–30, etc, while a center of 0 would give -5–5, 5–10, 10–20, etc. |
| cell_y_margin | Cell padding |
| height_mode | Height mode. Aspect ratio and fixed modes only work when embedding responsively with a script embed. Allowed values:"auto (cell aspect) |
| cell_height | Height. Height of each cell in rems (multiple of base font size) |
| cell_aspect | Aspect. Aspect ratio (width/height) of each cell |






## See Also
 Other Flourish heatmap or hierarchy charts:  `bind_circle_packing_data()`, `bind_heatmap_data()`, `bind_hierarchical_bar_data()`, `bind_hierarchy_data`, `bind_radial_tree_data()`, `bind_sunburst_data()`, `bind_treemap_data()`, `set_circle_packing_details()`, `set_hierarchical_bar_details()`, `set_radial_tree_details()`, `set_sunburst_details()`, `set_treemap_details()` 

