---
title: "Set Gantt details"
---

*R/details.R*

## set_gantt_details

## Description
 Set Gantt details 


## Usage
```r
 
set_gantt_details( 
  ., 
  gantt_height = NULL, 
  gantt_padding = NULL, 
  border_radius = NULL, 
  border_width = NULL, 
  border_color = NULL, 
  show_gantt_progress = NULL, 
  show_gantt_text = NULL, 
  gantt_label_font_size = NULL, 
  gantt_text_color = NULL, 
  gantt_font_weight = NULL, 
  missing_value_label = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| gantt_height | Height. Choose the height of each bar in rems (i.e. it will scale up and down in relation to screen size). Min: 1. Max: 5 |
| gantt_padding | Padding. Max: 1 |
| border_radius | Border radius. maximum 20. |
| border_width | Border width. Max: 1. |
| border_color | Border color. |
| show_gantt_progress | Show progress. If enabled, each bar will be filled with an overlay relating to the value supplied in the"Progress" column. Boolean (True/False). |
| show_gantt_text | Boolean (True/False) |
| gantt_label_font_size | Font size |
| gantt_text_color | Text color |
| gantt_font_weight | Font weight;"bold","normal" |
| missing_value_label | Label for missing values |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_slope_details()`, `set_word_cloud_details()` 

