---
title: "Set Flourish connections globe details"
---

*R/details.R*

## set_connections_globe_details

## Description
 Set Flourish connections globe details 


## Usage
```r
 
set_connections_globe_details( 
  ., 
  globe_skin = NULL, 
  globe_skin_other = NULL, 
  arrow_color = NULL, 
  accent_color = NULL, 
  selected_color = NULL, 
  grad_color = NULL, 
  grad_opacity = NULL, 
  custom_controls_colors = NULL, 
  controls_background_color = NULL, 
  controls_button_border = NULL, 
  controls_text_color = NULL, 
  aggregation_method = NULL, 
  arrow_scale_reference = NULL, 
  num_arrows = NULL, 
  arrow_scale = NULL, 
  auto_rotate = NULL, 
  distance = NULL, 
  default_latitude = NULL, 
  default_longitude = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| globe_skin | string Globe surface. Allowed values: world_blue.jpg (Blue), world_brown.jpg (Brown), world_blue_white.jpg (Blue & white), nasa_blue_marble.jpg (Satellite), seven_col_earth.png (Seven-color map), custom (Upload your own globe skin..) |
| globe_skin_other | url Upload globe surface skin. Provide a 4096x2048-pixel jpg file. |
| arrow_color | color Arrows. |
| accent_color | color Accent. |
| selected_color | color Arrow highlight. |
| grad_color | color color. When not set, gradient color will be same as background color |
| grad_opacity | number Opacity. Max: 1 |
| custom_controls_colors | boolean Customise controls colors. |
| controls_background_color | color Background. |
| controls_button_border | color Border. |
| controls_text_color | color Label. |
| aggregation_method | string If multiple rows with same locations.... Allowed values: sum (Sum the values), max (Use the maximum value), min (Use the minimum value), mean (Calculate the mean value), median (Calculate the median value), count (Count the number of values) |
| arrow_scale_reference | string Scale arrows relative to max value. Allowed values: all (All rows), current (Visible rows) |
| num_arrows | number Max number of arrows. Sets a limit on the number of arrows to draw to improve animation performance |
| arrow_scale | number Arrow scale. Multiplier to increase or decrease the width of the arrows |
| auto_rotate | boolean Auto rotate globe based on data. |
| distance | number Initial zoom. The distance from the earth, from 350 (closest) to 1000 (farthest away). Min: 350. Max: 1000 |
| default_latitude | number Default lat. The latitude to show on load. Ignored when Auto rotate is selected and there are arrows showing. Min: -90. Max: 90 |
| default_longitude | number Default long. The longitude to show on load. Ignored when Auto rotate is selected and there are arrows showing. Min: -180. Max: 180 |






## See Also
 Other Flourish map:  `bind_arc_map_data()`, `bind_choropleth_map_data()`, `bind_connections_globe_data()`, `bind_region_marker_map_data()`, `bind_time_map_data()`, `set_arc_map_details()`, `set_choropleth_map_details()`, `set_marker_map_details()`, `set_region_map_details()`, `set_time_map_details()` 

