---
title: "Set slope details"
---

*R/details.R*

## set_slope_details

## Description
 Set slope details 


## Usage
```r
 
set_slope_details( 
  ., 
  circle_radius = NULL, 
  slope_width = NULL, 
  slope_width_maximum = NULL, 
  line_curve = NULL, 
  highlighted_slopes = NULL, 
  only_show_highlights = NULL, 
  value_type = NULL, 
  ties_mode = NULL, 
  sort_mode = NULL, 
  height_mode = NULL, 
  aspect_ratio = NULL, 
  slope_color = NULL, 
  labels_name_position = NULL, 
  labels_position = NULL, 
  labels_inline_position = NULL, 
  labels_inline_position_custom_label = NULL, 
  labels_inline_position_custom_position = NULL, 
  line_end_labels_max_width = NULL, 
  line_end_labels_text_padding_horizontal = NULL, 
  line_end_labels_position = NULL, 
  line_end_labels_text_padding_vertical = NULL, 
  line_end_labels_hide_overlaps = NULL, 
  line_end_labels_text_color = NULL, 
  line_end_labels_text_size = NULL, 
  line_end_labels_text_bg_color = NULL, 
  line_end_labels_text_bg_size = NULL, 
  line_end_labels_text_line_height = NULL, 
  line_end_labels_text_max_lines = NULL, 
  line_end_labels_text_weight = NULL, 
  line_end_labels_connector_lines = NULL, 
  line_end_labels_connector_lines_style = NULL, 
  line_end_labels_connector_lines_color = NULL, 
  line_end_labels_connector_lines_width = NULL, 
  line_end_labels_connector_lines_range = NULL, 
  line_end_labels_connector_lines_padding = NULL 
) 
```

## Arguments
|Arguments|Description|
|---|---|
| . | The prior Flourish object. No need to specify name if piping graph as the graph will take the first argument (i.e. the prior existing graph). |
| circle_radius | Circle radius. |
| slope_width | Slope width. |
| slope_width_maximum | maximum slope width |
| line_curve | Line curve. Allowed values:"linear (step). |
| highlighted_slopes | A vector of highlighted slopes. |
| only_show_highlights | Only show highlighted data. Boolean (True/False). |
| value_type | Visualize value type. Allowed values:"ranks","scores","change" (percentage change). |
| ties_mode | Ties mode. What rank ranks should be given when there are ties? See https://en.wikipedia.org/wiki/Ranking for explanation of nomenclature. Allowed values:"densemodified_competition (1 3 3 4). |
| sort_mode | Sort mode. Allowed values:"descending","ascending". |
| height_mode | Height mode. Allowed values:"auto","aspect ratio". |
| aspect_ratio | Aspect ratio. 1 for square, a smaller value = bigger height. |
| slope_color | Slope color. Single value; if not set, will use same color as main text. |
| labels_name_position | Slope name mode. Allowed values:"side","inline". |
| labels_position | Slope name position."Both on narrow windows and devices. |
| labels_inline_position | Slope name inline position. Allowed values:"start","middle","end" |
| labels_inline_position_custom_label | Custom slope label |
| labels_inline_position_custom_position | Custom slope position. Allowed values:"start","middle","end". |
| line_end_labels_max_width | maximum label width. The maximum allowed label width |
| line_end_labels_text_padding_horizontal | Distance. The horizontal space between the data point and the label |
| line_end_labels_position | Spread out overlaps. Whether to spread out labels to minimise overlapping. Allowed values: spread-y (On), none (Off) |
| line_end_labels_text_padding_vertical | Vertical padding. The vertical space left between labels when spreading them out to avoid overlaps |
| line_end_labels_hide_overlaps | Hide overlaps. Whether to hide any labels that are overlapping in their final position |
| line_end_labels_text_color | Color. If cleared, uses the main text color from the Layout settings panel |
| line_end_labels_text_size | Size. Max: 100 |
| line_end_labels_text_bg_color | Outline. If cleared, uses the main background color from the Layout settings panel |
| line_end_labels_text_bg_size | Outline width. As a % of the font size Max: 100 |
| line_end_labels_text_line_height | Line height |
| line_end_labels_text_max_lines | maximum lines per label |
| line_end_labels_text_weight | Text weight. Allowed values:"normal","bold" |
| line_end_labels_connector_lines | Connector lines. Allowed values: auto (Auto), on (On), off (Off) |
| line_end_labels_connector_lines_style | Line style. Allowed values: straight (Straight), step (Step) |
| line_end_labels_connector_lines_color | Color. If cleared, uses the main text color from the Layout settings panel |
| line_end_labels_connector_lines_width | Width. In rems (a multiple of base font size). Max: 0.5 |
| line_end_labels_connector_lines_range | Length. The width of the space given over to lines; in rems, a multiple of base font size |
| line_end_labels_connector_lines_padding | Padding. The padding to the left and right of the line; in rems, a multiple of base font size |






## See Also
 Other Other Flourish graphs:  `bind_card_data()`, `bind_chord_diagram_data()`, `bind_gantt_data()`, `bind_network_data()`, `bind_pictogram_data()`, `bind_radar_data()`, `bind_sankey_data()`, `bind_slope_data()`, `bind_word_cloud_data()`, `set_card_details()`, `set_chord_diagram_details()`, `set_countdown_details()`, `set_gantt_details()`, `set_network_details()`, `set_photo_slider_details()`, `set_pictogram_details()`, `set_radar_details()`, `set_sankey_details()`, `set_word_cloud_details()` 

